### ISSUE TITLE
sqlmap itself said to report

### ISSUE THREAD

**Issue by ashee69** [sqlmapproject/sqlmap#1130]
this text i got while running a command
[09:30:59] [CRITICAL] unhandled exception in sqlmap/1.0-dev, retry your run with the latest development version from the GitHub repository. If the exception persists, please send by e-mail to 'sqlmap-users@lists.sourceforge.net' or open a new issue at 'https://github.com/sqlmapproject/sqlmap/issues/new' with the following text and any information required to reproduce the bug. The developers will try to reproduce the bug, fix it accordingly and get back to you.
sqlmap version: 1.0-dev
Python version: 2.7.3
Operating system: posix
Command line: ./sqlmap -u ************************************************** --random-agent -D ****** -T ******* --dump --threads=10 --start=53850 --stop=53860
Technique: None
Back-end DBMS: None (identified)
Traceback (most recent call last):
  File "./sqlmap", line 95, in main
    start()
  File "/usr/share/sqlmap/lib/controller/controller.py", line 362, in start
    setupTargetEnv()
  File "/usr/share/sqlmap/lib/core/target.py", line 590, in setupTargetEnv
    _resumeHashDBValues()
  File "/usr/share/sqlmap/lib/core/target.py", line 347, in _resumeHashDBValues
    for injection in hashDBRetrieve(HASHDB_KEYS.KB_INJECTIONS, True) or []:
  File "/usr/share/sqlmap/lib/core/common.py", line 3568, in hashDBRetrieve
    retVal = conf.hashDB.retrieve(_, unserialize) if kb.resumeValues and not (checkConf and any((conf.flushSession, conf.freshQueries))) else None
  File "/usr/share/sqlmap/lib/utils/hashdb.py", line 72, in retrieve
    for row in self.cursor.execute("SELECT value FROM storage WHERE id=?", (hash_,)):
OperationalError: Could not decode to UTF-8 column 'value' with text 'gAJdcQBjbGliLmNvcmUuZGF0YXR5cGUKSW5qZWN0aW9uRGljdApxASmBcQIoVQRkYm1zcQNVBU15U1FMcQRVBnN1ZmZpeHEFVRpBTkQgJ1tSQU5EU1RSXSc9J1tSQU5EU1RSXXEGVQZjbGF1c2
and please tell me something about .bin files that i got in result. so many things r missing in my result, may be they re hidden in .bin file.

**Comment by stamparm** [comment]
Which revision do you use? For a long time there is no a report like this
with missing any kind of revision information (e.g. v1.0-dev-xyzwvq)
