### ISSUE TITLE
Don't fail when SSL support is not enabled in Python's ssl module

### ISSUE THREAD

**Issue by rhertzog** [sqlmapproject/sqlmap#1193]
Trying to run sqlmap on a Debian Jessie system will lead to failures like this one:
```
root@kali:~# sqlmap -u "http://192.168.11.251/wp/" --dbs
Traceback (most recent call last):
  File "./sqlmap", line 22, in <module>
    from lib.controller.controller import start
  File "/usr/share/sqlmap/lib/controller/controller.py", line 61, in <module>
    from lib.core.target import initTargetEnv
  File "/usr/share/sqlmap/lib/core/target.py", line 40, in <module>
    from lib.core.option import _setDBMS
  File "/usr/share/sqlmap/lib/core/option.py", line 140, in <module>
    from lib.request.httpshandler import HTTPSHandler
  File "/usr/share/sqlmap/lib/request/httpshandler.py", line 22, in <module>
    _protocols = [ssl.PROTOCOL_SSLv3, ssl.PROTOCOL_TLSv1, ssl.PROTOCOL_SSLv23]
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'
```

That's because libssl has been compiled without SSLv2/SSLv3 support and the Python ssl module does the same when it gets built, those constants are no longer existing. So you should update your code to be able to cope with those missing constants.

**Comment by stamparm** [comment]
Fixed 4 months ago with https://github.com/sqlmapproject/sqlmap/commit/a0d95a8ec49ab0b41bd39c2bb537cb1d9bc07b9d
