### ISSUE TITLE
REST api database is locked

### ISSUE THREAD

**Issue by pnigos** [sqlmapproject/sqlmap#1226]
When using thread sending requests to sqlmap api ,after several times this error always raised.
llTraceback (most recent call last):
  File "/opt/sqlmap/thirdparty/bottle/bottle.py", line 763, in _handle
    return route.call(**args)
  File "/opt/sqlmap/thirdparty/bottle/bottle.py", line 1627, in wrapper
    rv = callback(*a, **ka)
  File "/opt/sqlmap/thirdparty/bottle/bottle.py", line 1577, in wrapper
    rv = callback(*a, **ka)
  File "/opt/sqlmap/lib/utils/api.py", line 525, in scan_data
    (taskid,)):
  File "/opt/sqlmap/lib/utils/api.py", line 81, in execute
    self.cursor.execute(statement, arguments)
OperationalError: database is locked

**Comment by stamparm** [comment]
Fixed with https://github.com/sqlmapproject/sqlmap/commit/a94dcf94e9772347e259cddec93f777160e9eca9
