### ISSUE TITLE
"OSError: [Errno 24] Too many open files" in sqlmap REST api server

### ISSUE THREAD

**Issue by pnigos** [sqlmapproject/sqlmap#1240]
After run sqlmapapi.py for a long time,error below always raised.
Traceback (most recent call last):
  File "/opt/sqlmap/thirdparty/bottle/bottle.py", line 763, in _handle
    return route.call(**args)
  File "/opt/sqlmap/thirdparty/bottle/bottle.py", line 1627, in wrapper
    rv = callback(*a, **ka)
  File "/opt/sqlmap/thirdparty/bottle/bottle.py", line 1577, in wrapper
    rv = callback(*a, **ka)
  File "/opt/sqlmap/lib/utils/api.py", line 459, in scan_start
    DataStore.tasks[taskid].engine_start()
  File "/opt/sqlmap/lib/utils/api.py", line 158, in engine_start
    shell=False, stdin=PIPE, close_fds=False)
  File "/usr/lib/python2.7/subprocess.py", line 672, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "/usr/lib/python2.7/subprocess.py", line 1038, in _get_handles
    p2cread, p2cwrite = self.pipe_cloexec()
  File "/usr/lib/python2.7/subprocess.py", line 1091, in pipe_cloexec
    r, w = os.pipe()
OSError: [Errno 24] Too many open files

**Comment by stamparm** [comment]
There is no reason to use `close_fds=True` introduced with [1]. Also, [2] states that's a very bad thing to do.

Reference:
[1] https://github.com/sqlmapproject/sqlmap/commit/1152cf8958eee13e827503812f3902f01d7a9c8f
[2] http://blog.juanl.org/python/2013/06/21/what-not-to-do-in-python.html
