### ISSUE TITLE
sqlmap crash

### ISSUE THREAD

**Issue by fate0** [sqlmapproject/sqlmap#1277]
```
python sqlmap.py -u 'http://www.target.com/mysql/get_int_rand.php?id=1%5Cg<hello>&ida=test'
```

```
sqlmap version: 1.0-dev-7d418af
Python version: 2.7.6
Operating system: posix
Command line: sqlmap.py -u **********************************************************************
Technique: None
Back-end DBMS: None (identified)
Traceback (most recent call last):
  File "sqlmap.py", line 102, in main
    start()
  File "lib/controller/controller.py", line 502, in start
    check = heuristicCheckSqlInjection(place, parameter)
  File "lib/controller/checks.py", line 836, in heuristicCheckSqlInjection
    payload = agent.payload(place, parameter, newValue=payload)
  File "lib/core/agent.py", line 185, in payload
    retVal = _(regex, "%s=%s" % (parameter, self.addPayloadDelimiters(newValue.replace("\\", "\\\\"))), paramString)
  File "lib/core/agent.py", line 177, in _
    repl = repl.replace(_.group(0), match.group(int(_.group(1)) if _.group(1).isdigit() else _.group(1)))
IndexError: no such group
```

**Comment by tennc** [comment]
url not in "%"
you can python sqlmap.py -u '''http://www.target.com/mysql/get_int_rand.php?id=1%5Cg<hello>&ida=test'''

or  %5c --> uUrlDecode --> "\"
