### ISSUE TITLE
SQLMap hits unhandled exception when crawling site

### ISSUE THREAD

**Issue by ColenMcA** [sqlmapproject/sqlmap#1284]
Hi there,

Here's the information sqlmap produces for the exception. Please let me know if there's any other details that would help.

[22:55:22] [CRITICAL] unhandled exception occurred in sqlmap/1.0-dev-nongit-20150629. It is recommended to retry your run with the latest development version from official GitHub repository at 'https://github.com/sqlmapproject/sqlmap'. If the exception persists, please open a new issue at 'https://github.com/sqlmapproject/sqlmap/issues/new' with the following text and any other information required to reproduce the bug. The developers will try to reproduce the bug, fix it accordingly and get back to you
sqlmap version: 1.0-dev-nongit-20150629
Python version: 2.7.10
Operating system: nt
Command line: sqlmap.py -u ******************************** --forms --crawl=10 --dbms=mssql --level=5 --risk=3 --batch
Technique: None
Back-end DBMS: Microsoft SQL Server (identified)
Traceback (most recent call last):
  File "sqlmap.py", line 102, in main
    start()
  File "lib/controller/controller.py", line 374, in start
    if not checkConnection(suppressOutput=conf.forms) or not checkString() or not checkRegexp():
  File "lib/controller/checks.py", line 1286, in checkConnection
    page, _ = Request.queryPage(content=True, noteResponseTime=False)
  File "lib/request/connect.py", line 1052, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "lib/request/connect.py", line 434, in getPage
    conn = urllib2.urlopen(req)
  File "Python27/lib/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "Python27/lib/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "Python27/lib/urllib2.py", line 449, in _open
    '_open', req)
  File "Python27/lib/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "Python27/lib/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "Python27/lib/urllib2.py", line 1194, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "Python27/lib/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "Python27/lib/httplib.py", line 1092, in _send_request
    self.putheader(hdr, value)
  File "Python27/lib/httplib.py", line 1031, in putheader
    raise ValueError('Invalid header value %r' % (one_value,))
ValueError: Invalid header value 'multipart/form-data; boundary=---------------------------78733635911017717001669269957\r'

**Comment by stamparm** [comment]
@ColenMcA we don't "craft" header values out from crawling/form parsing results, so this is kind of awkward. Is there a possibility to either send the URL and/or the traffic file (by appending the ...-t traffic.txt for one such run) to the `miroslav@sqlmap.org`?

**Comment by stamparm** [comment]
@ColenMcA ping?

**Comment by ColenMcA** [comment]
Email sent with the details.

**Comment by stamparm** [comment]
Unreproducible. Tried on Windows XP and Windows 7.
