### ISSUE TITLE
sqlmapapi Too many open files error

### ISSUE THREAD

**Issue by pnigos** [sqlmapproject/sqlmap#1292]
I use multiprocessing to call sqlmapapi.py to deploy scan task.After scanning for a few hours,the error blow always raised.I submit this issue once ago at https://github.com/sqlmapproject/sqlmap/issues/1240 but it still happened now.

Traceback (most recent call last):
  File "/opt/sqlmap/thirdparty/bottle/bottle.py", line 763, in _handle
    return route.call(**args)
  File "/opt/sqlmap/thirdparty/bottle/bottle.py", line 1627, in wrapper
    rv = callback(*a, **ka)
  File "/opt/sqlmap/thirdparty/bottle/bottle.py", line 1577, in wrapper
    rv = callback(*a, **ka)
  File "/opt/sqlmap/lib/utils/api.py", line 460, in scan_start
    DataStore.tasks[taskid].engine_start()
  File "/opt/sqlmap/lib/utils/api.py", line 159, in engine_start
    shell=False, stdin=PIPE, close_fds=not IS_WIN)
  File "/usr/lib/python2.7/subprocess.py", line 672, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "/usr/lib/python2.7/subprocess.py", line 1038, in _get_handles
    p2cread, p2cwrite = self.pipe_cloexec()
  File "/usr/lib/python2.7/subprocess.py", line 1091, in pipe_cloexec
    r, w = os.pipe()
OSError: [Errno 24] Too many open files

**Comment by stamparm** [comment]
How many tasks are there running?

**Comment by pnigos** [comment]
I run fifteen processes concurrently,each process has two threads to deploy scan task using sqlmapapi.py.The max concurrent scan task number is 30.I wait every three seconds to call api to check the task status
