### ISSUE TITLE
Client certificate --auth-private crashes

### ISSUE THREAD

**Issue by amlwwalker** [sqlmapproject/sqlmap#1434]
When passing the private key to sqlmap for authorization against a server, the following error occurs.

`sqlmap -u http://www.somewebaddress.com --auth-private private.pem`

```
[09:59:54] [CRITICAL] unhandled exception occurred in sqlmap/1.0-dev-38541b0. It is recommended to retry your run with the latest development version from official GitHub repository at 'https://github.com/sqlmapproject/sqlmap'. If the exception persists, please open a new issue at 'https://github.com/sqlmapproject/sqlmap/issues/new' with the following text and any other information required to reproduce the bug. The developers will try to reproduce the bug, fix it accordingly and get back to you
sqlmap version: 1.0-dev-38541b0
Python version: 2.7.9
Operating system: posix
Command line: sqlmap.py -u ****************************************************** --auth-private ../welcome.pem
Technique: None
Back-end DBMS: None (identified)
Traceback (most recent call last):
  File "sqlmap.py", line 110, in main
    start()
  File "lib/controller/controller.py", line 377, in start
    if not checkConnection(suppressOutput=conf.forms) or not checkString() or not checkRegexp():
  File "lib/controller/checks.py", line 1321, in checkConnection
    page, _ = Request.queryPage(content=True, noteResponseTime=False)
  File "lib/request/connect.py", line 1065, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "lib/request/connect.py", line 438, in getPage
    conn = urllib2.urlopen(req)
  File "usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "lib/request/pkihandler.py", line 19, in https_open
    return self.do_open(self.getConnection, req)
  File "usr/lib/python2.7/urllib2.py", line 1166, in do_open
    h = http_class(host, timeout=req.timeout, **http_conn_args)
  File "lib/request/pkihandler.py", line 22, in getConnection
    return httplib.HTTPSConnection(host, key_file=self.key_file, timeout=conf.timeout)
  File "usr/lib/python2.7/httplib.py", line 1198, in __init__
    context.load_cert_chain(cert_file, key_file)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

**Comment by stamparm** [comment]
Related bug: https://bugzilla.redhat.com/show_bug.cgi?id=1250611

**Comment by stamparm** [comment]
It should be patch (hopefully) now.

p.s. option `--auth-private` is now renamed to `--auth-file`
