### ISSUE TITLE
mac os el capitan use sqlmap problem

### ISSUE THREAD

**Issue by huakairuoxiangxi** [sqlmapproject/sqlmap#1530]
sqlmap  version 0.9 
mac os el capitan 10.11.1 (15B42)
```python
python sqlmap.py 
Traceback (most recent call last):
  File "/opt/application/PentestTool/sqlmap/sqlmap.py", line 22, in <module>
    from lib.controller.controller import start
  File "/opt/application/PentestTool/sqlmap/lib/controller/controller.py", line 11, in <module>
    from lib.controller.action import action
  File "/opt/application/PentestTool/sqlmap/lib/controller/action.py", line 8, in <module>
    from lib.controller.handler import setHandler
  File "/opt/application/PentestTool/sqlmap/lib/controller/handler.py", line 26, in <module>
    from plugins.dbms.mssqlserver import MSSQLServerMap
  File "/opt/application/PentestTool/sqlmap/plugins/dbms/mssqlserver/__init__.py", line 11, in <module>
    from plugins.dbms.mssqlserver.enumeration import Enumeration
  File "/opt/application/PentestTool/sqlmap/plugins/dbms/mssqlserver/enumeration.py", line 31, in <module>
    from plugins.generic.enumeration import Enumeration as GenericEnumeration
  File "/opt/application/PentestTool/sqlmap/plugins/generic/enumeration.py", line 18, in <module>
    from plugins.generic.custom import Custom
  File "/opt/application/PentestTool/sqlmap/plugins/generic/custom.py", line 22, in <module>
    from lib.core.shell import autoCompletion
  File "/opt/application/PentestTool/sqlmap/lib/core/shell.py", line 11, in <module>
    import rlcompleter
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/rlcompleter.py", line 166, in <module>
    import readline
  File "/Library/Python/2.7/site-packages/readline.py", line 6, in <module>
    from pyreadline.rlmain import Readline
  File "/Library/Python/2.7/site-packages/pyreadline/__init__.py", line 12, in <module>
    from . import logger, clipboard, lineeditor, modes, console
  File "/Library/Python/2.7/site-packages/pyreadline/clipboard/__init__.py", line 13, in <module>
    from .win32_clipboard import GetClipboardText, SetClipboardText
  File "/Library/Python/2.7/site-packages/pyreadline/clipboard/win32_clipboard.py", line 37, in <module>
    import ctypes.wintypes as wintypes
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/wintypes.py", line 23, in <module>
    class VARIANT_BOOL(_SimpleCData):
ValueError: _type_ 'v' not supported

before update mac os el capitan 10.11.1 (15B42)  sqlmap still can runing well.
```

**Comment by stamparm** [comment]
Wrong readline is used. I can make a patch, but `pyreadline` is used instead of regular `https://docs.python.org/2/library/readline.html`
