### ISSUE TITLE
Sqlmap bug after update

### ISSUE THREAD

**Issue by nsonaniya2010** [sqlmapproject/sqlmap#1550]
root@Edwards:~# sqlmap -u "http://vlnsite/page.php?tId=1"  --dbs --random-agent 
         _
 ___ ___| |_____ ___ ___  {1.0-dev-nongit-20151120}
|_ -| . | |     | .'| . |
|___|_  |_|_|_|_|__,|  _|
      |_|           |_|   http://sqlmap.org

[!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual consent is illegal. It is the end user's responsibility to obey all applicable local, state and federal laws. Developers assume no liability and are not responsible for any misuse or damage caused by this program

[*] starting at 20:14:57

[20:14:57] [INFO] fetched random HTTP User-Agent header from file '/usr/share/sqlmap/txt/user-agents.txt': 'Mozilla/5.0 (X11; U; Linux i686; pl-PL; rv:1.9.0.1) Gecko/2008071222 Firefox/3.0.1'
[20:14:59] [INFO] testing connection to the target URL
[20:15:29] [CRITICAL] unable to connect to the target URL or proxy. sqlmap is going to retry the request(s)
[20:15:29] [WARNING] if the problem persists please check that the provided target URL is valid. In case that it is, you can try to rerun with the switch '--random-agent' turned on and/or proxy switches ('--ignore-proxy', '--proxy',...)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/share/sqlmap/lib/core/option.py", line 1033, in _
    s._connect(address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
TypeError: getsockaddrarg() takes exactly 2 arguments (4 given)

[20:16:59] [CRITICAL] unable to connect to the target URL or proxy

[*] shutting down at 20:16:59

**Comment by stamparm** [comment]
Can you please help me to reproduce the problem? Have you used any other switches/options? Are you able to reproduce it each time you run it?

**Comment by stamparm** [comment]
This looks like IPv6 has been used. Most probably Python does some black magic (on socket.connect) in switching from IPv4 to IPv6 support.

Can you please send me more details to `miroslav@sqlmap.org`?

**Comment by stamparm** [comment]
That's it. I've blindly implemented support for IPv4 while skipping IPv6. Will fix

**Comment by stamparm** [comment]
Thank you for your report :)

**Comment by nsonaniya2010** [comment]
Thankyou :)

**Comment by nsonaniya2010** [comment]
Done thnankyou :+1:
