### ISSUE TITLE
Database name retrieve not decoded

### ISSUE THREAD

**Issue by sombra2eternity** [sqlmapproject/sqlmap#1579]
Using --hex during enumeration sqlmap dont decode back the database name when it end encapsulated in quotes.

Example:

[23:40:55] [INFO] retrieved: 696E666F726D61746
[23:40:55] [INFO] retrieved: 70617472696D6F6E696F32

[...]

available databases [2]:
[* ] \`696E666F726D61746`
[* ] xxxxxx

More info: 
- - -
Parameter: xxxxxxx (GET)
    Type: AND/OR time-based blind
    Title: MySQL >= 5.0.12 AND time-based blind (SELECT)
    Payload: espacio_id=5 AND (SELECT * FROM (SELECT(SLEEP(5)))OGtS)
- - -

Thanks so much :-)

**Comment by stamparm** [comment]
That `696E666F726D61746` failed because it hasn't completed successfully

```
stamparm@Laptop:~/Dropbox/Work/sqlmap$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> "696E666F726D61746".decode("hex")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/encodings/hex_codec.py", line 42, in hex_decode
    output = binascii.a2b_hex(input)
TypeError: Odd-length string
>>> "696E666F726D6174".decode("hex")
'informat'
>>> 
```

**Comment by stamparm** [comment]
@sombra2eternity with the latest revision you'll be warned about such cases and sqlmap will try to fail-safe decode it

**Comment by sombra2eternity** [comment]
Yes, it should be information_schema, complete output was:

[...]
[23:28:31] [INFO] adjusting time delay to 3 seconds due to good response times
[23:28:53] [INFO] retrieved: 2
[23:40:55] [INFO] retrieved: 696E666F726D61746
[23:40:55] [INFO] retrieved: 70617472696D6F6E696F32
[23:56:24] [ERROR] invalid character detected. retrying..
[23:56:24] [WARNING] increasing time delay to 4 seconds 
[23:56:29] [INFO] retrieved: patrimonio2
available databases [2]:
[ *] \`696E666F726D61746`
[ *] patrimonio2
[...]

Maybe it should not be listed on error or show some kind of message, the "[23:56:24] [ERROR]" line seems to be related to the second database and sugest its going to retry :S
