### ISSUE TITLE
Unhandled exception (#eabfbeec)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#1758]
```
sqlmap version: 1.0-dev-nongit-201603120a89
Python version: 2.7.9
Operating system: posix
Command line: /usr/bin/sqlmap -u **************************************** and 11-1 --technique=BUES --random-agent --tamper=between -f -b --dbs --level=5 --risk=3
Technique: BOOLEAN
Back-end DBMS: None (identified)
```
```
Traceback (most recent call last):
  File "sqlmap", line 100, in main
    start()
  File "share/sqlmap/lib/controller/controller.py", line 522, in start
    injection = checkSqlInjection(place, parameter, value)
  File "share/sqlmap/lib/controller/checks.py", line 685, in checkSqlInjection
    injection = checkFalsePositives(injection)
  File "share/sqlmap/lib/controller/checks.py", line 770, in checkFalsePositives
    if checkBooleanExpression("%d=%d" % (randInt1, randInt3)):
  File "share/sqlmap/lib/request/inject.py", line 490, in checkBooleanExpression
    return getValue(expression, expected=EXPECTED.BOOL, charsetType=CHARSET_TYPE.BINARY, suppressOutput=True, expectingNone=expectingNone)
  File "share/sqlmap/lib/request/inject.py", line 427, in getValue
    value = _goBooleanProxy(booleanExpression)
  File "share/sqlmap/lib/request/inject.py", line 313, in _goBooleanProxy
    output = hashDBRetrieve(expression, checkConf=True)
  File "share/sqlmap/lib/core/common.py", line 3854, in hashDBRetrieve
    """
  File "share/sqlmap/lib/utils/hashdb.py", line 79, in retrieve
    while True:
OperationalError: no such table: storage
```

**Comment by stamparm** [comment]
Update to the latest revision
