### ISSUE TITLE
OperationalError: unable to open database file

### ISSUE THREAD

**Issue by ghost** [sqlmapproject/sqlmap#193]
EDIT: There seems to be a problem with the disk on my side, but you could handle the error anyway. Thanks!

[02:11:10] [CRITICAL] unhandled exception in sqlmap/1.0-dev, retry your run with the latest development version from the GitHub repository. If the exception persists, please send by e-mail to 'sqlmap-users@lists.sourceforge.net' or open a new issue at 'https://github.com/sqlmapproject/sqlmap/issues/new' with the following text and any information required to reproduce the bug. The developers will try to reproduce the bug, fix it accordingly and get back to you.
sqlmap version: 1.0-dev
Python version: 2.7.3
Operating system: posix
Command line: ./sqlmap.py --tor --check-tor -o -u *****************************\* -D *********\* -T ***\* --dump
Technique: BOOLEAN
Back-end DBMS: Microsoft SQL Server (fingerprinted)
Traceback (most recent call last):
  File "/media/truecrypt1/Documents/DUMPS/sqlmap/_sqlmap.py", line 72, in main
  File "/media/truecrypt1/Documents/DUMPS/sqlmap/lib/controller/controller.py", line 564, in start
  File "/media/truecrypt1/Documents/DUMPS/sqlmap/lib/controller/action.py", line 110, in action
  File "/media/truecrypt1/Documents/DUMPS/sqlmap/plugins/generic/entries.py", line 246, in dumpTable
  File "/media/truecrypt1/Documents/DUMPS/sqlmap/lib/utils/pivotdumptable.py", line 113, in pivotDumpTable
  File "/media/truecrypt1/Documents/DUMPS/sqlmap/lib/request/inject.py", line 424, in getValue
  File "/media/truecrypt1/Documents/DUMPS/sqlmap/lib/request/inject.py", line 320, in __goInferenceProxy
  File "/media/truecrypt1/Documents/DUMPS/sqlmap/lib/request/inject.py", line 116, in __goInferenceFields
  File "/media/truecrypt1/Documents/DUMPS/sqlmap/lib/request/inject.py", line 88, in __goInference
  File "/media/truecrypt1/Documents/DUMPS/sqlmap/lib/techniques/blind/inference.py", line 416, in bisection
  File "/media/truecrypt1/Documents/DUMPS/sqlmap/lib/core/threads.py", line 199, in runThreads
  File "/media/truecrypt1/Documents/DUMPS/sqlmap/lib/utils/hashdb.py", line 103, in flush
OperationalError: unable to open database file

**Comment by MoTechStore** [comment]
[03:33:03] [CRITICAL] unable to connect to the target URL ('Too many open files'). sqlmap is going to retry the request(s)

anyone to hel me on this ?

**Comment by stamparm** [comment]
@MoTechStore there is zero useful information in your upper comment

**Comment by MoTechStore** [comment]
[04:59:04] [WARNING] there has been a problem while writing to the session file ('unable to open database file')
sorry for asking more questions ,,,

**Comment by MoTechStore** [comment]
i will be asking when i fail

**Comment by MoTechStore** [comment]
i scanned a target using two vuln scanners , one found sql injection but another did not , i step ahead by using sqlmap to explot vuln , then i was faces with above challenge
[04:59:04] [WARNING] there has been a problem while writing to the session file ('unable to open database file')
