### ISSUE TITLE
'NoneType' object has no attribute 'items' from sqlmap API

### ISSUE THREAD

**Issue by brandonprry** [sqlmapproject/sqlmap#2108]
Hello,

Trying to start a task scan with a POST and some JSON. Not sure when this started but this happens on latest.

```
$ curl 127.0.0.1:8775/task/new
{
    "taskid": "3ecb6bd723ddda2d", 
    "success": true
}
$ curl -X POST --data '{"url":"http://testfire.net"}' 127.0.0.1:8775/scan/3ecb6bd723ddda2d/start
Internal server error
$
```

The stack trace on the server side.

```
$ ./sqlmapapi.py --server
[09:06:53] [INFO] Running REST-JSON API server at '127.0.0.1:8775'..
[09:06:53] [INFO] Admin ID: 96137ae48a20329a096562905f92f34a
[09:06:53] [DEBUG] IPC database: /var/folders/nq/h6g3jtv510jfkhw_2y0d58yc0000gn/T/sqlmapipc-amou61
[09:06:53] [DEBUG] REST-JSON API server connected to IPC database
[09:06:53] [DEBUG] Using adapter 'wsgiref' to run bottle
[09:06:57] [DEBUG] Created new task: 'dc0228d41359dc1c'
Traceback (most recent call last):
  File "/Users/bperry/Projects/sqlmap/thirdparty/bottle/bottle.py", line 935, in _inner_handle
    return route.call(**args)
  File "/Users/bperry/Projects/sqlmap/thirdparty/bottle/bottle.py", line 1888, in wrapper
    rv = callback(*a, **ka)
  File "/Users/bperry/Projects/sqlmap/lib/utils/api.py", line 471, in scan_start
    for option, value in request.json.items():
AttributeError: 'NoneType' object has no attribute 'items'
```

Any thoughts?

**Comment by brandonprry** [comment]
Ugh, I'm an idiot.

**Comment by brandonprry** [comment]
(missing -H "Content-Type: application/json")
