### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by himanshudas** [sqlmapproject/sqlmap#2188]
Hello @stamparm,

Kindly help with following exception:
```
[21:51:22] [ERROR] invalid character detected. retrying..
[21:51:22] [WARNING] increasing time delay to 5 seconds
[21:51:22] [WARNING] HTTP error codes detected during run:
503 (Service Unavailable) - 1 times
[21:51:22] [DEBUG] too many 4xx and/or 5xx HTTP error codes could mean that some kind of protection is involved (e.g. WAF)

[21:51:22] [DEBUG] running code integrity check
[21:51:23] [CRITICAL] unhandled exception occurred in sqlmap/1.0.9.20#dev. It is recommended to retry your run with the latest development version from official GitHub repository at 'https://github.com/sqlmapproject/sqlmap'. If the exception persists, please open a new issue at 'https://github.com/sqlmapproject/sqlmap/issues/new' with the following text and any other information required to reproduce the bug. The developers will try to reproduce the bug, fix it accordingly and get back to you
sqlmap version: 1.0.9.20#dev
Python version: 2.6.6
Operating system: posix
Command line: sqlmap.py -r test -p test_param -v3 --dbms=MySQL --random-agent -D **** -T **** --columns **** --dump --no-cast --batch --retries=10
Technique: STACKED
Back-end DBMS: MySQL (fingerprinted)
Traceback (most recent call last):
  File "sqlmap.py", line 149, in main
    start()
  File "lib/controller/controller.py", line 633, in start
    action()
  File "lib/controller/action.py", line 121, in action
    conf.dbmsHandler.dumpTable()
  File "plugins/generic/entries.py", line 330, in dumpTable
    value = NULL if column in emptyColumns else inject.getValue(query, union=False, error=False, dump=True)
  File "lib/request/inject.py", line 445, in getValue
    value = _goInferenceProxy(query, fromUser, batch, unpack, charsetType, firstChar, lastChar, dump)
  File "lib/request/inject.py", line 285, in _goInferenceProxy
    outputs = _goInferenceFields(expression, expressionFields, expressionFieldsList, payload, charsetType=charsetType, firstChar=firstChar, lastChar=lastChar, dump=dump)
  File "lib/request/inject.py", line 128, in _goInferenceFields
    output = _goInference(payload, expressionReplaced, charsetType, firstChar, lastChar, dump, field)
  File "lib/request/inject.py", line 100, in _goInference
    count, value = bisection(payload, expression, length, charsetType, firstChar, lastChar, dump)
  File "lib/techniques/blind/inference.py", line 579, in bisection
    val = getChar(index, asciiTbl)
  File "lib/techniques/blind/inference.py", line 375, in getChar
    return getChar(idx, originalTbl, continuousOrder, expand, shiftTable, (retried or 0) + 1)
  File "lib/techniques/blind/inference.py", line 375, in getChar
    return getChar(idx, originalTbl, continuousOrder, expand, shiftTable, (retried or 0) + 1)
  File "lib/techniques/blind/inference.py", line 272, in getChar
    position = charTbl.index(ord('a') - 1)  # 96
AttributeError: 'xrange' object has no attribute 'index'

do you want to automatically create a new (anonymized) issue with the unhandled exception information at the official Github repository? [y/N] > N
[21:51:23] [DEBUG] used the default behaviour, running in batch mode

[*] shutting down at 21:51:23
```

**Comment by stamparm** [comment]
Please, just update to the latest revision (currently 1.0.9.34#dev). This has been fixed three days ago ( Issue #2175)
