### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by JonhSilver** [sqlmapproject/sqlmap#2311]
[09:06:24] [ERROR] thread MainThread: unhandled exception occurred in sqlmap/1.0
.10.29#dev. It is recommended to retry your run with the latest development vers
ion from official GitHub repository at 'https://github.com/sqlmapproject/sqlmap'
. If the exception persists, please open a new issue at 'https://github.com/sqlm
approject/sqlmap/issues/new' with the following text and any other information r
equired to reproduce the bug. The developers will try to reproduce the bug, fix
it accordingly and get back to you
sqlmap version: 1.0.10.29#dev
Python version: 2.7.11
Operating system: nt
Command line: sqlmap.py -u https://site.com/Naty/*_Naty_4i__sht.html --tor --tor-port=9150 --tor-type=socks5 --check-tor --batch --random-agent --level=5 --risk=3 --answers=redirect=y --crawl=1 --forms
Technique: None
Back-end DBMS: None (identified)
Traceback (most recent call last):
  File "C:\Python27\sqlmap\lib\core\threads.py", line 142, in runThreads
    threadFunction()
  File "C:\Python27\sqlmap\lib\utils\crawler.py", line 117, in crawlThread
    findPageForms(content, current, False, True)
  File "C:\Python27\sqlmap\lib\core\common.py", line 3794, in findPageForms
    _ = reduce(lambda x, y: x == y, map(lambda x: urlparse.urlparse(x).netloc.sp
lit(':')[0], (response.geturl(), url)))
  File "C:\Python27\sqlmap\lib\core\common.py", line 3794, in <lambda>
    _ = reduce(lambda x, y: x == y, map(lambda x: urlparse.urlparse(x).netloc.sp
lit(':')[0], (response.geturl(), url)))
  File "C:\Python27\lib\urlparse.py", line 143, in urlparse
    tuple = urlsplit(url, scheme, allow_fragments)
  File "C:\Python27\lib\urlparse.py", line 182, in urlsplit
    i = url.find(':')
AttributeError: 'NoneType' object has no attribute 'find'
do you want to store crawling results to a temporary file for eventual further p
rocessing with other tools [y/N] N
[09:06:24] [INFO] sqlmap got a total of 14 targets

**Comment by stamparm** [comment]
Fixed with latest commit (17c556a63db73da215854273c24c418784e84750)

**Comment by JonhSilver** [comment]
[09:09:54] [INFO] searching for links with depth 1
[09:09:57] [INFO] heuristics detected web page charset 'windows-1251'

[09:09:57] [ERROR] thread MainThread: unhandled exception occurred in sqlmap/1.0
.12.11#dev. It is recommended to retry your run with the latest development vers
ion from official GitHub repository at 'https://github.com/sqlmapproject/sqlmap'
. If the exception persists, please open a new issue at 'https://github.com/sqlm
approject/sqlmap/issues/new' with the following text and any other information r
equired to reproduce the bug. The developers will try to reproduce the bug, fix
it accordingly and get back to you
sqlmap version: 1.0.12.11#dev
Python version: 2.7.11
Operating system: nt
Command line: sqlmap.py -u https://site.com/Naty/*_Naty_4i__sht.html --tor --tor-port=9150 --tor-
type=socks5 --check-tor --batch --random-agent --level=5 --risk=3 --crawl=1 --fo
rms
Technique: None
Back-end DBMS: None (identified)
Traceback (most recent call last):
  File "C:\Python27\sqlmap\lib\core\threads.py", line 143, in runThreads
    threadFunction()
  File "C:\Python27\sqlmap\lib\utils\crawler.py", line 119, in crawlThread
    findPageForms(content, current, False, True)
  File "C:\Python27\sqlmap\lib\core\common.py", line 3813, in findPageForms
    _ = reduce(lambda x, y: x == y, map(lambda x: urlparse.urlparse(x).netloc.sp
lit(':')[0], (response.geturl(), url)))
  File "C:\Python27\sqlmap\lib\core\common.py", line 3813, in <lambda>
    _ = reduce(lambda x, y: x == y, map(lambda x: urlparse.urlparse(x).netloc.sp
lit(':')[0], (response.geturl(), url)))
  File "C:\Python27\lib\urlparse.py", line 143, in urlparse
    tuple = urlsplit(url, scheme, allow_fragments)
  File "C:\Python27\lib\urlparse.py", line 182, in urlsplit
    i = url.find(':')
AttributeError: 'NoneType' object has no attribute 'find'
do you want to store crawling results to a temporary file for eventual further p
rocessing with other tools [y/N] N
[09:09:57] [INFO] sqlmap got a total of 14 targets

**Comment by JonhSilver** [comment]
also sqlmap cant find injection as injection exist in browser by typing manually

**Comment by stamparm** [comment]
So, I've told you that it was fixed with latest commit (1.0.12.12) and you are still running old version (1.0.12.11). No comment
