### ISSUE TITLE
sqlmap api

### ISSUE THREAD

**Issue by qik23** [sqlmapproject/sqlmap#2415]
Hello,
I have installed sqilmap api on my server and trying to create a new task on my PC:
```
sqlmapapi.py -c -H "*server ip*"
[12:37:43] [DEBUG] Example client access from command line:
        $ taskid=$(curl http://*server ip*:8775/task/new 2>1 | grep -o -I '[a-f0-9]\{16\}') && echo $taskid
        $ curl -H "Content-Type: application/json" -X POST -d '{"url": "http://testphp.vulnweb.com/artists.php?artist=1"}' http://*server ip*:8775/scan/$taskid/start
        $ curl http://*server ip*:8775/scan/$taskid/data
        $ curl http://*server ip*:8775/scan/$taskid/log
[12:37:43] [INFO] Starting REST-JSON API client to 'http://*server ip*:8775'...
[12:37:43] [DEBUG] Calling http://*server ip*:8775
[12:37:43] [INFO] Type 'help' or '?' for list of available commands
api> new -m "/root/sqlmap-dev/exp.txt" --dbs
```
But i get error in client console:
```
[12:37:50] [DEBUG] Calling http://*server ip*:8775/task/new
[12:37:50] [INFO] New task ID is '2cfa000ce08c4b83'
[12:37:50] [DEBUG] Calling http://*server ip*:8775/scan/2cfa000ce08c4b83/start
[12:37:50] [ERROR] Failed to load and parse http://*server ip*:8775/scan/2cfa000ce08c4b83/start
Traceback (most recent call last):
  File "G:\sqlmap\sqlmapapi.py", line 54, in <module>
    main()
  File "G:\sqlmap\sqlmapapi.py", line 49, in main
    client(args.host, args.port)
  File "G:\sqlmap\lib\utils\api.py", line 774, in client
    raw = _client("%s/scan/%s/start" % (addr, taskid), cmdLineOptions)
  File "G:\sqlmap\lib\utils\api.py", line 694, in _client
    response = urllib2.urlopen(req)
  File "G:\Python\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "G:\Python\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "G:\Python\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "G:\Python\lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "G:\Python\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "G:\Python\lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 500: Internal Server Error
```
And in server console:
```
[12:37:49] [DEBUG] Created new task: '2cfa000ce08c4b83'
Traceback (most recent call last):                                                                                                                            
  File "/root/sqlmap-dev/thirdparty/bottle/bottle.py", line 935, in _inner_handle                                                                             
    return route.call(**args)                                                                                                                                 
  File "/root/sqlmap-dev/thirdparty/bottle/bottle.py", line 1888, in wrapper                                                                                  
    rv = callback(*a, **ka)                                                                                                                                   
  File "/root/sqlmap-dev/lib/utils/api.py", line 478, in scan_start                                                                                           
    DataStore.tasks[taskid].engine_start()                                                                                                                    
  File "/root/sqlmap-dev/lib/utils/api.py", line 170, in engine_start                                                                                         
    self.process = Popen(["sqlmap", "--pickled-options", base64pickle(self.options)], shell=False, close_fds=not IS_WIN)                                      
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__                                                                                              
    errread, errwrite)                                                                                                                                        
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child                                                                                       
    raise child_exception                                                                                                                                     
OSError: [Errno 2] No such file or directory       
```                                                                                                           
I tried different ways to set a path to exp.txt:
```
new -m "exp.txt" --dbs
new -m "/sqlmap-dev/exp.txt" --dbs
etc
```
and got the same error. 
exp.txt have 777 permission if it does matter.
If im trying to use `-u "URL"` instead of `-m` everything is ok.
Am i wrong in something?

**Comment by stamparm** [comment]
Basically, you have copied somehow the sqlmap installation with `sqlmapapi.py` but without the `sqlmap.py` inside. There are 3 different scenarios inside the `sqlmapapi.py` to search for `sqlmap.py` and it failed to find it in any way. Closing this down as invalid

**Comment by qik23** [comment]
I copied sqlmap via git:
`git clone --depth 1 https://github.com/sqlmapproject/sqlmap.git sqlmap-dev`
then just lauch `sqlmapapi.py` on my server like:
`./sqlmapapi.py -s -H "*server ip*" `
I just reinstalled it and got same error.
It works if I use `new -u "URL" --dbs` but it didnt work when I try `new -m "exp.txt" --dbs`
exp.txt placed in same folder as `sqlmap.py` and `sqlmapapi.py`

**Comment by stamparm** [comment]
![1](https://cloud.githubusercontent.com/assets/921555/23380029/7e50641c-fd39-11e6-95b0-9abadc17aa53.png)
![2](https://cloud.githubusercontent.com/assets/921555/23380028/7e4f612a-fd39-11e6-9d96-1287010c8276.png)
![3](https://cloud.githubusercontent.com/assets/921555/23380031/7e58468c-fd39-11e6-9763-62d899f0007e.png)
