### ISSUE TITLE
ValueError: database parameter must be string or APSW Connection object

### ISSUE THREAD

**Issue by tcordon** [sqlmapproject/sqlmap#2471]
## What's the problem (or question)?
sqlmap version: 1.1.4.13#dev
Python version: 2.7.9
Operating system: posix
Command line: sqlmap.py -u ***************************************************************************************************** None
Back-end DBMS: None
Traceback (most recent call last):
  File "sqlmap.py", line 135, in main
    setRestAPILog()
  File "lib/utils/api.py", line 288, in setRestAPILog
    conf.databaseCursor.connect("client")
  File "lib/utils/api.py", line 73, in connect
    self.connection = sqlite3.connect(self.database, timeout=3, isolation_level=None)
ValueError: database parameter must be string or APSW Connection object

## Do you have an idea for a solution?
no
## How can we reproduce the issue?
Downloaded today's commit c74756c3bc983fce7349832a2962d6023ff384d0 (Mon Apr 10 16:44:12 2017 +0200)
> git clone --depth 1 https://github.com/sqlmapproject/sqlmap.git sqlmap-dev
> python sqlmap.py -u "one_url"

**Comment by tcordon** [comment]
Fixed! thank you!!
