### ISSUE TITLE
MemoryError after Dumping

### ISSUE THREAD

**Issue by SecurityFlaw** [sqlmapproject/sqlmap#2487]
Hi guys.

I got these error messages:
Traceback (most recent call last):
  File "C:\Tools\sqlmap-dev\thirdparty\ansistrm\ansistrm.py", line 55, in emit
    message = stdoutencode(self.format(record))
  File "C:\Tools\sqlmap-dev\thirdparty\ansistrm\ansistrm.py", line 157, in format
    message = logging.StreamHandler.format(self, record)
  File "C:\Python27\lib\logging\__init__.py", line 734, in format
  File "C:\Tools\sqlmap-dev\lib\core\option.py", line 463, in format
  File "C:\Python27\lib\logging\__init__.py", line 467, in format
  File "C:\Python27\lib\logging\__init__.py", line 425, in formatTime
MemoryError
Logged from file connect.py, line 806
Traceback (most recent call last):
  File "C:\Tools\sqlmap-dev\thirdparty\ansistrm\ansistrm.py", line 55, in emit
    message = stdoutencode(self.format(record))
  File "C:\Tools\sqlmap-dev\thirdparty\ansistrm\ansistrm.py", line 157, in format
    message = logging.StreamHandler.format(self, record)
  File "C:\Python27\lib\logging\__init__.py", line 734, in format
  File "C:\Tools\sqlmap-dev\lib\core\option.py", line 463, in format
  File "C:\Python27\lib\logging\__init__.py", line 467, in format
  File "C:\Python27\lib\logging\__init__.py", line 425, in formatTime
MemoryError
Logged from file threads.py, line 99
[16:19:30] [DEBUG] performed 1486939 queries in 24477.64 seconds

[16:20:03] [DEBUG] running code integrity check

[*] shutting down at 16:20:03

Traceback (most recent call last):
  File "C:\Tools\sqlmap-dev\sqlmap.py", line 351, in <module>
    main()
  File "C:\Tools\sqlmap-dev\sqlmap.py", line 205, in main
    valid = checkIntegrity()
  File "C:\Tools\sqlmap-dev\lib\core\common.py", line 3204, in checkIntegrity
    elif hashlib.md5(open(path, 'rb').read()).hexdigest() != checksum:
MemoryError

Screenshot: http://i.imgur.com/E9CaELL.png

Dump was running over 3 Days. Maybe that's the Problem?

**Comment by stamparm** [comment]
Which version of sqlmap do you use and how much memory do you have on that box?

**Comment by stamparm** [comment]
I see what could cause this. Will patch (maybe this moment if I catch time)

**Comment by stamparm** [comment]
Made a minor patch, but I am pretty sure that it won't fix your problem. As asked before, which version of sqlmap do you use and how much memory do you have on that box?

**Comment by stamparm** [comment]
Closing due to lack of user response

**Comment by SecurityFlaw** [comment]
Sorry guys, i had no time to answer faster!
sqlmap was on version 1.1.4.27#dev.
RAM is on 16 GB.

**Comment by stamparm** [comment]
Can you please check if you used 32-bit python (Similar problem: http://stackoverflow.com/questions/4441947/why-python-memory-error-with-list-append-lots-of-ram-left)?

You can check with `python -c "import platform; print platform.architecture()[0]"`

If so, please download and install 64-bit version and rerun the sqlmap

**Comment by stamparm** [comment]
@SecurityFlaw anyway, checking the problem in its core

**Comment by stamparm** [comment]
Found a bug and fixed with the latest commit/revision. Please update and retry it again. There was indeed a memory problem where buffered items haven't been "flushed" properly (to lower the memory consumption)

**Comment by SecurityFlaw** [comment]
Seems fixed!
