### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by JonhSilver** [sqlmapproject/sqlmap#2520]
[12:35:36] [INFO] recognized possible password hashes in column 'user_info_id'
do you want to crack them via a dictionary-based attack? [Y/n/q] Y
[12:35:36] [INFO] using hash method 'md5_generic_passwd'
[12:35:36] [INFO] starting dictionary-based cracking (md5_generic_passwd)
Process Process-43:
Traceback (most recent call last):
  File "c:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "c:\Python27\lib\multiprocessing\process.py", line 114, in run
 P   self._target(*self._args, **self._kwargs)
rocess Process-46:
TTPypeError: _bruteProcessVariantA() takes exactly 9 arguments (8 given)
Praceback (most recent call last):
rocess Process-47:
rocess Process-42:
 TT File "c:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
raceback (most recent call last):
raceback (most recent call last):
      self.run()
 File "c:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
 File "c:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
    File "c:\Python27\lib\multiprocessing\process.py", line 114, in run
   self.run()
   self.run()
      self._target(*self._args, **self._kwargs)
 File "c:\Python27\lib\multiprocessing\process.py", line 114, in run
 File "c:\Python27\lib\multiprocessing\process.py", line 114, in run
T  ypeError: _bruteProcessVariantA() takes exactly 9 arguments (8 given)
   self._target(*self._args, **self._kwargs)
   self._target(*self._args, **self._kwargs)
TTypeError: _bruteProcessVariantA() takes exactly 9 arguments (8 given)
ypeError: _bruteProcessVariantA() takes exactly 9 arguments (8 given)
Process Process-44:
Traceback (most recent call last):
 P File "c:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
rocess Process-48:
P TProcess Process-45:
   self.run()
raceback (most recent call last):
rocess Process-41:
T  Traceback (most recent call last):
 File "c:\Python27\lib\multiprocessing\process.py", line 114, in run
 File "c:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
raceback (most recent call last):
     File "c:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
   self._target(*self._args, **self._kwargs)
   self.run()
 File "c:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
 T     self.run()
ypeError: _bruteProcessVariantA() takes exactly 9 arguments (8 given)
 File "c:\Python27\lib\multiprocessing\process.py", line 114, in run
   self.run()
    File "c:\Python27\lib\multiprocessing\process.py", line 114, in run
   self._target(*self._args, **self._kwargs)
 File "c:\Python27\lib\multiprocessing\process.py", line 114, in run
 T    self._target(*self._args, **self._kwargs)
ypeError: _bruteProcessVariantA() takes exactly 9 arguments (8 given)
   self._target(*self._args, **self._kwargs)
TTypeError: _bruteProcessVariantA() takes exactly 9 arguments (8 given)
ypeError: _bruteProcessVariantA() takes exactly 9 arguments (8 given)

**Comment by stamparm** [comment]
In both https://github.com/sqlmapproject/sqlmap/blob/master/lib/utils/hash.py#L845 and https://github.com/sqlmapproject/sqlmap/blob/master/lib/utils/hash.py#L861 there are 9 provided arguments. I guess that you messed something up while updating the sqlmap. Please get everything from this repository and rerun.
