### ISSUE TITLE
 [ERROR] thread MainThread: unhandled exception occurred in sqlmap/1.1 .4.45#dev

### ISSUE THREAD

**Issue by JonhSilver** [sqlmapproject/sqlmap#2543]
[14:27:55] [ERROR] thread MainThread: unhandled exception occurred in sqlmap/1.1
.4.45#dev. It is recommended to retry your run with the latest development versi
on from official GitHub repository at 'https://github.com/sqlmapproject/sqlmap'.
 If the exception persists, please open a new issue at 'https://github.com/sqlma
pproject/sqlmap/issues/new' with the following text and any other information re
quired to reproduce the bug. The developers will try to reproduce the bug, fix i
t accordingly and get back to you
sqlmap version: 1.1.4.45#dev
Python version: 2.7.13
Operating system: nt
Command line: sqlmap.py --tor --batch --threads=10 --drop-set-cookie --no-cast -
-random-agent -m sss.txt --crawl 1 --forms
Technique: None
Back-end DBMS: None
Traceback (most recent call last):
  File "c:\python27\sqlmap\lib\core\threads.py", line 142, in runThreads
    threadFunction()
  File "c:\python27\sqlmap\lib\utils\crawler.py", line 64, in crawlThread
    content = Request.getPage(url=current, crawling=True, raise404=False)[0]
  File "c:\python27\sqlmap\lib\request\connect.py", line 463, in getPage
    conn = urllib2.urlopen(req)
  File "c:\python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "c:\python27\lib\urllib2.py", line 421, in open
    protocol = req.get_type()
  File "c:\python27\lib\urllib2.py", line 283, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: dyiaa.com
[14:27:55] [WARNING] no usable links found (with GET parameters)

[14:27:55] [ERROR] user aborted

[*] shutting down at 14:27:55

**Comment by JonhSilver** [comment]
[14:32:10] [ERROR] thread MainThread: unhandled exception occurred in sqlmap/1.1
.5.9#dev. It is recommended to retry your run with the latest development versio
n from official GitHub repository at 'https://github.com/sqlmapproject/sqlmap'.
If the exception persists, please open a new issue at 'https://github.com/sqlmap
project/sqlmap/issues/new' with the following text and any other information req
uired to reproduce the bug. The developers will try to reproduce the bug, fix it
 accordingly and get back to you
sqlmap version: 1.1.5.9#dev
Python version: 2.7.13
Operating system: nt
Command line: sqlmap.py --tor --batch --threads=10 --drop-set-cookie --no-cast -
-random-agent -m sss.txt --crawl 1 --forms
Technique: None
Back-end DBMS: None
Traceback (most recent call last):
  File "c:\python27\sqlmap\lib\core\threads.py", line 142, in runThreads
    threadFunction()
  File "c:\python27\sqlmap\lib\utils\crawler.py", line 65, in crawlThread
    content = Request.getPage(url=current, crawling=True, raise404=False)[0]
  File "c:\python27\sqlmap\lib\request\connect.py", line 466, in getPage
    conn = urllib2.urlopen(req)
  File "c:\python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "c:\python27\lib\urllib2.py", line 421, in open
    protocol = req.get_type()
  File "c:\python27\lib\urllib2.py", line 283, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: m.yesmywine.com
[14:32:10] [WARNING] no usable links found (with GET parameters)

[14:32:10] [ERROR] user aborted

[*] shutting down at 14:32:10

**Comment by klensy** [comment]
Try to use http://example.com instead example.com in targets.
