### ISSUE TITLE
error while trying to decrypt hash

### ISSUE THREAD

**Issue by z3ro** [sqlmapproject/sqlmap#2642]
[01:56:06] [INFO] recognized possible password hashes in column 'password_sha1'
do you want to store hashes to a temporary file for eventual further processing
with other tools [y/N] n
do you want to crack them via a dictionary-based attack? [Y/n/q] y
[02:17:33] [INFO] using hash method 'sha1_generic_passwd'
what dictionary do you want to use?
[1] default dictionary file 'C:\py1\s4\txt\wordlist.zip' (press Enter)
[2] custom dictionary file
[3] file with list of dictionary files
> 1
[02:17:35] [INFO] using default dictionary
do you want to use common password suffixes? (slow!) [y/N] y
[02:17:37] [INFO] starting dictionary-based cracking (sha1_generic_passwd)
[02:17:37] [INFO] starting 2 processes
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\py1\lib\multiprocessing\forking.py", line 380, in main
    prepare(preparation_data)
  File "C:\py1\lib\multiprocessing\forking.py", line 489, in prepare
Traceback (most recent call last):
  File "<string>", line 1, in <module>
      File "C:\py1\lib\multiprocessing\forking.py", line 380, in main
file, path_name, etc = imp.find_module(main_name, dirs)
    ImportErrorprepare(preparation_data)
  File "C:\py1\lib\multiprocessing\forking.py", line 489, in prepare
    file, path_name, etc = imp.find_module(main_name, dirs)
ImportError: : NNo module named so module named s

**Comment by Ekultek** [comment]
Post the hashes..

**Comment by stamparm** [comment]
@z3ro you haven't copy pasted the whole error-report. You are missing the last `.so` module name.

This looks like an improper installation of Python, as you are missing precompiled `.so` module. You should uninstall previous version of Python and install it from the beginning.
