### ISSUE TITLE
Internal server error on RESTful API

### ISSUE THREAD

**Issue by Ekultek** [sqlmapproject/sqlmap#2680]
While trying to connect to the sqlmap API and start a scan I get an internal server error:
```

baal@baal-Aspire-5733Z:~/bin/python/sqlmap$ python sqlmapapi.py -s
[09:53:06] [INFO] Running REST-JSON API server at '127.0.0.1:8775'..
[09:53:06] [INFO] Admin ID: 08debff50b9dff202bb9f9fcbc25b75a
[09:53:06] [DEBUG] IPC database: '/tmp/sqlmapipc-9B7sFU'
[09:53:06] [DEBUG] REST-JSON API server connected to IPC database
[09:53:07] [DEBUG] Using adapter 'wsgiref' to run bottle
[09:53:17] [DEBUG] Created new task: '3ae8b7b74ec21c6e'
[09:53:17] [DEBUG] [3ae8b7b74ec21c6e] Retrieved scan status
[09:53:17] [DEBUG] [0] Listed task pool (127.0.0.1)
Traceback (most recent call last):
  File "/home/baal/bin/python/sqlmap/thirdparty/bottle/bottle.py", line 935, in _inner_handle
    return route.call(**args)
  File "/home/baal/bin/python/sqlmap/thirdparty/bottle/bottle.py", line 1888, in wrapper
    rv = callback(*a, **ka)
  File "/home/baal/bin/python/sqlmap/lib/utils/api.py", line 490, in scan_start
    for option, value in request.json.items():
AttributeError: 'NoneType' object has no attribute 'items'
```

How I'm starting the scan:

```
    def __init__(self, to_scan, port=None, api_con="http://127.0.0.1:{}", default_port=8775, opts=None):
        self.to_scan = to_scan
        if port is None:
            self.port = default_port
        else:
            self.port = port
        self.opts = opts
        self.headers = {"Content-Type": "application/json"}
        self.connection = api_con.format(self.port)
        self.commands = {
            "init": "/task/new",
            "id": "/admin/0/list",
            "start": "/scan/{}/start",
            "status": "/scan/{}/status",
            "log": "/scan/{}/log"
        }

    def init_new_scan(self):
        new_scan_url = "{}{}".format(self.connection, self.commands["init"])
        requests.get(new_scan_url, params=self.headers)

    def get_scan_id(self):
        id_re = re.compile(r"[a-fA-F0-9]{16}")
        api_id_url = "{}{}".format(self.connection, self.commands["id"])
        req = requests.get(api_id_url)
        to_check = str(json.loads(req.content)["tasks"]).lower()
        return ''.join(id_re.findall(to_check))

    def start_scan(self, api_id):
        start_scan_url = "{}{}".format(self.connection, self.commands["start"].format(api_id))
        requests.post(start_scan_url, data={"url": self.to_scan})
```
Now from the examples I've seen you have to pass the data as a dict to the /scan/ID/start URL, I also tried URL encoding the dict and it still seems to not have any effect. So my question to you, is, is this an issue on my end? Or is it an issue on the server end?

**Comment by Ekultek** [comment]
Also tried JSONizing the dict, same issue.

**Comment by stamparm** [comment]
Minimalistic client can be found at: https://github.com/sqlmapproject/sqlmap/blob/master/lib/utils/api.py#L716-L734.

In your case `data` should be "jsonized" and headers should be set to `{"Content-Type": "application/json"}`

**Comment by Ekultek** [comment]
Cool thanks man, much appreciated.

**Comment by Ekultek** [comment]
Worked like a charm, thank you sir
