### ISSUE TITLE
sqlmap API failing?

### ISSUE THREAD

**Issue by Ekultek** [sqlmapproject/sqlmap#2741]
## What's the problem (or question)?

I have an application that connects to sqlmap's API and runs a scan from the API, during the scanning I'm getting a 500 internal server error from my application, and a OSError from the sqlmapapi server.

## Do you have an idea for a solution?

I have a feeling its coming the the fact that sqlmap calls `sqlmap --api -c <FILE>` to run the API (that's what I've gathered anyways, correct me if I'm wrong)

## How can we reproduce the issue?

1. Run `sqlmapapi.py -s`
2. Connect to the API via thirdparty application
3. Try to initialize a scan 
4. Try to start the scan 
5. Should fail here

## What are the running context details?

* Installation method (e.g. `pip`, `apt-get`, `git clone` or `zip`/`tar.gz`): `git clone`
* Client OS (e.g. `Microsoft Windows 10`) Ubuntu 17.04
* Program version (`python sqlmap.py --version` or `sqlmap --version` depending on installation): `updated to the latest revision 'f9de8a8'`
* Target DBMS (e.g. `Microsoft SQL Server`): n/a
* Detected WAF/IDS/IPS protection (e.g. `ModSecurity` or `unknown`): n/a
* SQLi techniques found by sqlmap (e.g. `error-based` and `boolean-based blind`): n/a
* Results of manual target assessment (e.g. found that the payload `query=test' AND 4113 IN ((SELECT 'foobar'))-- qKLV` works): n/a
* Relevant console output (if any):
From my application when connecting:
```
[12:56:19 DEBUG] scan initialized...
[12:56:19 INFO] gathering sqlmap API scan ID...
[12:56:19 DEBUG] current sqlmap scan ID: 'd149235412f9237a'...
[12:56:19 INFO] starting sqlmap scan on url: 'https://*********.com/'...
[12:56:19 DEBUG] no arguments passed, skipping...
[12:56:19 WARNING] please keep in mind that this is the API, output will not be saved to log file, it may take a little longer to finish processing, launching sqlmap...
[12:56:19 ERROR] ran into error 'HTTP Error 500: Internal Server Error', seems something went wrong, error has been saved to current log file.
Traceback (most recent call last):
  File "/home/baal/bin/python/dev/zeus-scanner/lib/attacks/sqlmap_scan/__init__.py", line 176, in sqlmap_scan_main
    sqlmap_scan.start_scan(api_id, opts=opts)
  File "/home/baal/bin/python/dev/zeus-scanner/lib/attacks/sqlmap_scan/__init__.py", line 76, in start_scan
    return urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 500: Internal Server Error
```

From the sqlmap API itself:
```
baal@baal-Aspire-5733Z:~$ python bin/python/sqlmap/sqlmapapi.py -s
[12:53:45] [INFO] Running REST-JSON API server at '127.0.0.1:8775'..
[12:53:45] [INFO] Admin ID: 6e72d07bd65498d278ef3af0d55fe289
[12:53:45] [DEBUG] IPC database: '/tmp/sqlmapipc-oBBBIS'
[12:53:45] [DEBUG] REST-JSON API server connected to IPC database
[12:53:45] [DEBUG] Using adapter 'wsgiref' to run bottle
[12:56:19] [DEBUG] Created new task: 'd149235412f9237a'
[12:56:19] [DEBUG] [d149235412f9237a] Retrieved scan status
[12:56:19] [DEBUG] [0] Listed task pool (127.0.0.1)
Traceback (most recent call last):
  File "/home/baal/bin/python/sqlmap/thirdparty/bottle/bottle.py", line 935, in _inner_handle
    return route.call(**args)
  File "/home/baal/bin/python/sqlmap/thirdparty/bottle/bottle.py", line 1888, in wrapper
    rv = callback(*a, **ka)
  File "/home/baal/bin/python/sqlmap/lib/utils/api.py", line 502, in scan_start
    DataStore.tasks[taskid].engine_start()
  File "/home/baal/bin/python/sqlmap/lib/utils/api.py", line 176, in engine_start
    self.process = Popen(["sqlmap", "--api", "-c", configFile], shell=False, close_fds=not IS_WIN)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
* Exception traceback (if any): Same as above

**Comment by Ekultek** [comment]
(referencing for users)

**Comment by Ekultek** [comment]
Well re-cloning sqlmap did the trick, not sure what the problem was here.
