### ISSUE TITLE
i cannot retrieve any data from the targets i have executed before

### ISSUE THREAD

**Issue by azhari33** [sqlmapproject/sqlmap#2984]
this was happened 2 days ago

this is a warning i get

[18:52:03] [WARNING] (case) time-based comparison requires larger statistical model, please wait.............................. (done)
[18:53:35] [CRITICAL] considerable lagging has been detected in connection response(s). Please use as high value for option '--time-sec' as possible (e.g. 10 or more)
[18:53:41] [WARNING] it is very important to not stress the network connection during usage of time-based payloads to prevent potential disruptions 

[18:53:51] [WARNING] in case of continuous data retrieval problems you are advised to try a switch '--no-cast' or switch '--hex'
[18:53:51] [WARNING] (case) time-based comparison requires larger statistical model, please wait.............
[18:54:18] [WARNING] turning off pre-connect mechanism because of connection reset(s)
[18:54:18] [CRITICAL] connection reset to the target URL. sqlmap is going to retry the request(s)

<h3>even when i press CTRL + C, i get error like this</h3>

Traceback (most recent call last):
  File "/usr/local/bin/powerline-shell", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/powerline_shell/__init__.py", line 191, in main
    segment.add_to_powerline()
  File "/usr/local/lib/python2.7/dist-packages/powerline_shell/segments/hg.py", line 67, in add_to_powerline
    self.join()
  File "/usr/lib/python2.7/threading.py", line 940, in join
    self.__block.wait()
  File "/usr/lib/python2.7/threading.py", line 340, in wait
    waiter.acquire()
KeyboardInterrupt
^C
Traceback (most recent call last):
  File "/usr/local/bin/powerline-shell", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/powerline_shell/__init__.py", line 191, in main
    segment.add_to_powerline()
  File "/usr/local/lib/python2.7/dist-packages/powerline_shell/segments/git.py", line 93, in add_to_powerline
    self.join()
  File "/usr/lib/python2.7/threading.py", line 940, in join
    self.__block.wait()
  File "/usr/lib/python2.7/threading.py", line 340, in wait
    waiter.acquire()
KeyboardInterrupt

but before when i press CTRL + C, sqlmap directly outputs

**Comment by stamparm** [comment]
What seems to be the problem? You are sending here a traceback from "powerline-shell" which doesn't have anything to do with the sqlmap.

In your case you are getting some connection problems. I would suggest you to first check your shell and connection before raising this kind of issues.
