### ISSUE TITLE
SQLMAP not working on Mac OS High Siera 10.13.1 (17B1003)

### ISSUE THREAD

**Issue by Avinash-acid** [sqlmapproject/sqlmap#3027]
Looks like SQLMAP has some issues while running on Mac OS. Below is the stack trace for the issue:-

> MacBook-Pro:PEM Files acid$ sqlmap -h
Traceback (most recent call last):
  File "/usr/local/bin/sqlmap", line 66, in <module>
    from lib.parse.cmdline import cmdLineParser
  File "/usr/local/Cellar/sqlmap/1.2.4/libexec/lib/parse/cmdline.py", line 35, in <module>
    from lib.core.shell import autoCompletion
  File "/usr/local/Cellar/sqlmap/1.2.4/libexec/lib/core/shell.py", line 11, in <module>
    from lib.core import readlineng as readline
  File "/usr/local/Cellar/sqlmap/1.2.4/libexec/lib/core/readlineng.py", line 15, in <module>
    from readline import *
  File "/Library/Python/2.7/site-packages/readline.py", line 6, in <module>
    from pyreadline.rlmain import Readline
  File "/Library/Python/2.7/site-packages/pyreadline/__init__.py", line 12, in <module>
    from . import logger, clipboard, lineeditor, modes, console
  File "/Library/Python/2.7/site-packages/pyreadline/clipboard/__init__.py", line 13, in <module>
    from .win32_clipboard import GetClipboardText, SetClipboardText
  File "/Library/Python/2.7/site-packages/pyreadline/clipboard/win32_clipboard.py", line 37, in <module>
    import ctypes.wintypes as wintypes
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/wintypes.py", line 23, in <module>
    class VARIANT_BOOL(_SimpleCData):
ValueError: _type_ 'v' not supported

With a little bit googling, came to know that issue is SQLMAP is trying to import windows specific data types from ctypes which is not possible as I am running MacOS not windows.
  **File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/wintypes.py", line 23, in <module>
    class VARIANT_BOOL(_SimpleCData):
ValueError: _type_ 'v' not supported**

Please check, if there is any way to resolve this issue ?

Thanks,
<img width="970" alt="screen shot 2018-04-05 at 12 52 44 pm" src="https://user-images.githubusercontent.com/16536521/38356245-48cacf7a-38d0-11e8-9d88-25bc3af3db72.png">

**Comment by stamparm** [comment]
By taking a look into the stacktrace you can see that sqlmap just tries to import standard Python's library `readline`, while MacOS does the wrong data handling. Nevertheless, will patch

**Comment by Avinash-acid** [comment]
Thanks for the information.
