### ISSUE TITLE
Ctrl + C bug

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3258]
windows cmd: (newest version) `sqlmap.py --dependencies`
and.... `Ctrl + C`
```
Traceback (most recent call last):
  File "C:\Users\fku\Documents\fku\sqlmap-dev\sqlmap.py", line 36, in <module>
    from lib.core.data import logger
  File "C:\Users\fku\Documents\fku\sqlmap-dev\lib\core\data.py", line 9, in <module>
    from lib.core.log import LOGGER
  File "C:\Users\fku\Documents\fku\sqlmap-dev\lib\core\log.py", line 21, in <module>
    from thirdparty.ansistrm.ansistrm import ColorizingStreamHandler
  File "C:\Users\fku\Documents\fku\sqlmap-dev\thirdparty\ansistrm\ansistrm.py", line 12, in <module>
    from lib.core.convert import stdoutencode
  File "C:\Users\fku\Documents\fku\sqlmap-dev\lib\core\convert.py", line 21, in <module>
    from lib.core.settings import IS_WIN
  File "C:\Users\fku\Documents\fku\sqlmap-dev\lib\core\settings.py", line 9, in <module>
    import random
  File "C:\Python27\lib\random.py", line 49, in <module>
    import hashlib as _hashlib
  File "C:\Python27\lib\hashlib.py", line 56, in <module>
    """
KeyboardInterrupt
```

**Comment by huitc** [comment]
`sqlmap.py --dependencies -v 3`
`Ctrl + C`
```
Traceback (most recent call last):
  File "C:\Users\fku\Documents\fku\sqlmap-dev\sqlmap.py", line 13, in <module>
    __import__("lib.utils.versioncheck")  # this has to be the first non-standard import
  File "C:\Users\fku\Documents\fku\sqlmap-dev\lib\utils\versioncheck.py", line 19, in <module>
    __import__(_)
  File "C:\Python27\lib\ssl.py", line 95, in <module>
    from collections import namedtuple
  File "C:\Python27\lib\collections.py", line 22, in <module>
    from keyword import iskeyword as _iskeyword
  File "C:\Python27\lib\keyword.py", line 11, in <module>
    """
KeyboardInterrupt
```

**Comment by stamparm** [comment]
Bug of too fast pressing of a Ctrl-C (at time of library load, before sqlmap even starts to do anything)?
