### ISSUE TITLE
1 bug discovered during run.

### ISSUE THREAD

**Issue by AmericanY** [sqlmapproject/sqlmap#3268]
Traceback (most recent call last):
  File "/root/A/thirdparty/ansistrm/ansistrm.py", line 58, in emit
    message = stdoutencode(self.format(record))
  File "/root/A/thirdparty/ansistrm/ansistrm.py", line 202, in format
    return self.colorize(message, record.levelno)
  File "/root/A/thirdparty/ansistrm/ansistrm.py", line 184, in colorize
    string = re.search(r": '(.+)'", message).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
Logged from file basic.py, line 371

**Comment by stamparm** [comment]
Thx
