### ISSUE TITLE
Exception running on multiple targets 1.3.3.30#dev

### ISSUE THREAD

**Issue by raspberry-tips** [sqlmapproject/sqlmap#3538]
Exception running on multiple targets. 1.3.3.30#dev

```
Command line: sqlmap.py -m /root/1.txt --dbs --batch --forms --crawl=1 --crawl-exclude=logout --keep-alive --threads=10 --random-agent
Technique: None
Back-end DBMS: None
Traceback (most recent call last):
  File "/root/sqlmap-dev/lib/core/threads.py", line 145, in runThreads
    threadFunction()
  File "/root/sqlmap-dev/lib/utils/crawler.py", line 87, in crawlThread
    soup = BeautifulSoup(content)
  File "/root/sqlmap-dev/thirdparty/beautifulsoup/beautifulsoup.py", line 1526, in __init__
    BeautifulStoneSoup.__init__(self, *args, **kwargs)
  File "/root/sqlmap-dev/thirdparty/beautifulsoup/beautifulsoup.py", line 1151, in __init__
    self._feed(isHTML=isHTML)
  File "/root/sqlmap-dev/thirdparty/beautifulsoup/beautifulsoup.py", line 1193, in _feed
    SGMLParser.feed(self, markup)
  File "/usr/lib/python2.7/sgmllib.py", line 104, in feed
    self.goahead(0)
  File "/usr/lib/python2.7/sgmllib.py", line 138, in goahead
    k = self.parse_starttag(i)
  File "/usr/lib/python2.7/sgmllib.py", line 296, in parse_starttag
    self.finish_starttag(tag, attrs)
  File "/usr/lib/python2.7/sgmllib.py", line 345, in finish_starttag
    self.handle_starttag(tag, method, attrs)
  File "/usr/lib/python2.7/sgmllib.py", line 381, in handle_starttag
    method(attrs)
  File "/root/sqlmap-dev/thirdparty/beautifulsoup/beautifulsoup.py", line 1623, in start_meta
    tag = self.unknown_starttag("meta", attrs)
  File "/root/sqlmap-dev/thirdparty/beautifulsoup/beautifulsoup.py", line 1351, in unknown_starttag
    tag = Tag(self, name, attrs, self.currentTag, self.previous)
  File "/root/sqlmap-dev/thirdparty/beautifulsoup/beautifulsoup.py", line 566, in __init__
    self.attrs = map(convert, self.attrs)
TypeError: <lambda>() takes exactly 2 arguments (1 given)
```

**Comment by raspberry-tips** [comment]
Running version: 1.3.3.30#dev
Python version: 2.7.15+
Operating system: Linux-4.15.18-10-pve-x86_64-with-Ubuntu-18.10-cosmic

**Comment by CakeHunter** [comment]
I had the same error today with ubuntu , debian 8 and 9 .
