### ISSUE TITLE
problem about --chunk

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3541]
version: `46ee690`
`sqlmap.py --chunk -v 2 --null-connection --predict-output --level 5 --risk 2 --sqlmap-shell --random-agent --tamper randomcase,xforwardedfor,varnish`
`-r 2.txt --dbms mysql --os linux --dbs`
```
[21:55:46] [INFO] testing connection to the target URL

[21:55:47] [DEBUG] running code integrity check
[21:55:47] [ERROR] wrong checksum of file 'C:\Users\test\Documents\test\sqlmap-dev\COMMITMENT' detected
[21:55:47] [ERROR] wrong checksum of file 'C:\Users\test\Documents\test\sqlmap-dev\LICENSE' detected
[21:55:47] [ERROR] wrong checksum of file 'C:\Users\test\Documents\test\sqlmap-dev\thirdparty\odict\ordereddict.py' detected
[21:55:47] [CRITICAL] code integrity check failed (turning off automatic issue creation). You should retrieve the latest development version from official GitHub repository at 'https://github.com/sqlmapproject/sqlmap'

Traceback (most recent call last):
  File "sqlmap.py", line 171, in main
    start()
  File "C:\Users\test\Documents\test\sqlmap-dev\lib\core\decorators.py", line 53, in _
    result = f(*args, **kwargs)
  File "C:\Users\test\Documents\test\sqlmap-dev\lib\controller\controller.py", line 411, in start
    if not checkConnection(suppressOutput=conf.forms) or not checkString() or not checkRegexp():
  File "C:\Users\test\Documents\test\sqlmap-dev\lib\controller\checks.py", line 1571, in checkConnection
    page, headers, _ = Request.queryPage(content=True, noteResponseTime=False)
  File "C:\Users\test\Documents\test\sqlmap-dev\lib\core\decorators.py", line 53, in _
    result = f(*args, **kwargs)
  File "C:\Users\test\Documents\test\sqlmap-dev\lib\request\connect.py", line 1290, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "C:\Users\test\Documents\test\sqlmap-dev\lib\request\connect.py", line 281, in getPage
    post = urllib.unquote(post)
  File "C:\Python27\lib\urllib.py", line 1233, in unquote
    bits = s.split('%')
AttributeError: 'NoneType' object has no attribute 'split'

[*] ending @ 21:55:47 /2019-03-19/
```
@boy-hack

**Comment by boy-hack** [comment]
I guess the get request  in -r ？

**Comment by huitc** [comment]
都是中國人就說中文吧....

**Comment by huitc** [comment]
給我你的emaill~

**Comment by stamparm** [comment]
Fixed with latest revision. POST body was most probably empty (as @boy-hack noted)

**Comment by stamparm** [comment]
@huitc how do you get those `wrong checksum` warnings? Do you get it by default?

**Comment by huitc** [comment]
`-v 2`?

**Comment by stamparm** [comment]
Fixed with aa1020a3d1cc71532e68067fbbb99e5152bdf5ac

**Comment by huitc** [comment]
yeah!! but I didn't edit anything...

**Comment by huitc** [comment]
nice~!

**Comment by stamparm** [comment]
@huitc can you please zip those problematic files and send it to me (`miroslav@sqlmap.org`)?

**Comment by huitc** [comment]
sent!! @stamparm @boy-hack
