### ISSUE TITLE
ImportError: No module named compat

### ISSUE THREAD

**Issue by thistehneisen** [sqlmapproject/sqlmap#3555]
## What's the problem (or question)?

Tried on both OS X and Ubuntu Server, outputting ImportError: No module named compat

## How can we reproduce the issue?

x@y:~/sqlmap-dev$ python sqlmap.py
Traceback (most recent call last):
  File "sqlmap.py", line 40, in <module>
    from lib.core.common import banner
  File "/home/influent/sqlmap-dev/lib/core/common.py", line 59, in <module>
    from lib.core.decorators import cachedmethod
  File "/home/influent/sqlmap-dev/lib/core/decorators.py", line 14, in <module>
    from lib.core.threads import getCurrentThreadData
  File "/home/influent/sqlmap-dev/lib/core/threads.py", line 16, in <module>
    from lib.core.compat import WichmannHill
ImportError: No module named compat

## What are the running context details?

git cloned from github

**Comment by stamparm** [comment]
@thistehneisen my fault. Doing lots of modifications. Find it patched now
