### ISSUE TITLE
When the network is unstable. . .

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3588]
```
...
[01:44:59] [INFO] retrieved: _175_46__F_9______ 7/18 (38%)
```
and then..
```
[01:45:02] [CRITICAL] unable to connect to the target URL ('Network is unreachable'). sqlmap is going to retry the request(s)
[01:45:02] [WARNING] if the problem persists please try to lower the number of used threads (option '--threads')
[01:45:02] [DEBUG] unable to connect to the target URL ('Network is unreachable'). sqlmap is going to retry the request
[01:45:02] [DEBUG] unable to connect to the target URL ('Network is unreachable'). sqlmap is going to retry the request
[01:45:02] [CRITICAL] unable to connect to the target URL ('Network is unreachable')
[01:45:02] [WARNING] unexpected HTTP code 'None' detected. Will use (extra) validation step in similar cases
[01:45:02] [CRITICAL] unable to connect to the target URL ('Network is unreachable'). sqlmap is going to retry the request(s)
[01:45:02] [DEBUG] unable to connect to the target URL ('Network is unreachable'). sqlmap is going to retry the request
[01:45:02] [DEBUG] unable to connect to the target URL ('Network is unreachable'). sqlmap is going to retry the request
[01:45:02] [CRITICAL] unable to connect to the target URL ('Network is unreachable')
[01:45:02] [CRITICAL] unable to connect to the target URL ('Network is unreachable'). sqlmap is going to retry the request(s)
[01:45:02] [DEBUG] unable to connect to the target URL ('Network is unreachable'). sqlmap is going to retry the request
[01:45:02] [DEBUG] unable to connect to the target URL ('Network is unreachable'). sqlmap is going to retry the request
[01:45:02] [CRITICAL] unable to connect to the target URL ('Network is unreachable')
[01:45:02] [CRITICAL] unable to connect to the target URL ('Network is unreachable'). sqlmap is going to retry the request(s)
[01:45:02] [DEBUG] unable to connect to the target URL ('Network is unreachable'). sqlmap is going to retry the request
there seems to be a continuous problem with connection to the target. Are you sure that you want to continue with further target testing? [y/N] N
[01:45:02] [DEBUG] used the default behavior, running in batch mode
[01:45:02] [ERROR] thread 3: ''
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/sqlmap/lib/core/threads.py", line 93, in exceptionHandledFunction
    threadFunction()
  File "/data/data/com.termux/files/home/sqlmap/lib/techniques/blind/inference.py", line 477, in blindThread
    val = getChar(currentCharIndex, asciiTbl, not(charsetType is None and conf.charset))
  File "/data/data/com.termux/files/home/sqlmap/lib/techniques/blind/inference.py", line 339, in getChar
    result = Request.queryPage(forgedPayload, timeBasedCompare=timeBasedCompare, raise404=False)
  File "/data/data/com.termux/files/home/sqlmap/lib/core/decorators.py", line 53, in _
    result = f(*args, **kwargs)
  File "/data/data/com.termux/files/home/sqlmap/lib/request/connect.py", line 1301, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "/data/data/com.termux/files/home/sqlmap/lib/request/connect.py", line 750, in getPage
    return Connect._retryProxy(**kwargs)
  File "/data/data/com.termux/files/home/sqlmap/lib/request/connect.py", line 192, in _retryProxy
    return Connect._getPageProxy(**kwargs)
  File "/data/data/com.termux/files/home/sqlmap/lib/request/connect.py", line 138, in _getPageProxy
    return Connect.getPage(**kwargs)
  File "/data/data/com.termux/files/home/sqlmap/lib/request/connect.py", line 750, in getPage
    return Connect._retryProxy(**kwargs)
  File "/data/data/com.termux/files/home/sqlmap/lib/request/connect.py", line 192, in _retryProxy
    return Connect._getPageProxy(**kwargs)
  File "/data/data/com.termux/files/home/sqlmap/lib/request/connect.py", line 138, in _getPageProxy
    return Connect.getPage(**kwargs)
  File "/data/data/com.termux/files/home/sqlmap/lib/request/connect.py", line 736, in getPage
    raise SqlmapUserQuitException
SqlmapUserQuitException
[01:45:02] [ERROR] thread 8: ''
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/sqlmap/lib/core/threads.py", line 93, in exceptionHandledFunction
    threadFunction()
  File "/data/data/com.termux/files/home/sqlmap/lib/techniques/blind/inference.py", line 477, in blindThread
    val = getChar(currentCharIndex, asciiTbl, not(charsetType is None and conf.charset))
  File "/data/data/com.termux/files/home/sqlmap/lib/techniques/blind/inference.py", line 339, in getChar
    result = Request.queryPage(forgedPayload, timeBasedCompare=timeBasedCompare, raise404=False)
  File "/data/data/com.termux/files/home/sqlmap/lib/core/decorators.py", line 53, in _
    result = f(*args, **kwargs)
  File "/data/data/com.termux/files/home/sqlmap/lib/request/connect.py", line 1301, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "/data/data/com.termux/files/home/sqlmap/lib/request/connect.py", line 736, in getPage
    raise SqlmapUserQuitException
SqlmapUserQuitException
[01:45:02] [ERROR] thread 0: ''
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/sqlmap/lib/core/threads.py", line 93, in exceptionHandledFunction
    threadFunction()
  File "/data/data/com.termux/files/home/sqlmap/lib/techniques/blind/inference.py", line 477, in blindThread
    val = getChar(currentCharIndex, asciiTbl, not(charsetType is None and conf.charset))
  File "/data/data/com.termux/files/home/sqlmap/lib/techniques/blind/inference.py", line 339, in getChar
    result = Request.queryPage(forgedPayload, timeBasedCompare=timeBasedCompare, raise404=False)
  File "/data/data/com.termux/files/home/sqlmap/lib/core/decorators.py", line 53, in _
    result = f(*args, **kwargs)
  File "/data/data/com.termux/files/home/sqlmap/lib/request/connect.py", line 1301, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "/data/data/com.termux/files/home/sqlmap/lib/request/connect.py", line 736, in getPage
    raise SqlmapUserQuitException
SqlmapUserQuitException
[01:45:02] [ERROR] thread 7: ''
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/sqlmap/lib/core/threads.py", line 93, in exceptionHandledFunction
[01:45:02] [ERROR] thread 5: ''
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/sqlmap/lib/core/threads.py", line 93, in exceptionHandledFunction
    threadFunction()
  File "/data/data/com.termux/files/home/sqlmap/lib/techniques/blind/inference.py", line 477, in blindThread
    val = getChar(currentCharIndex, asciiTbl, not(charsetType is None and conf.charset))
  File "/data/data/com.termux/files/home/sqlmap/lib/techniques/blind/inference.py", line 339, in getChar
    result = Request.queryPage(forgedPayload, timeBasedCompare=timeBasedCompare, raise404=False)
[01:45:02] [ERROR] thread 1: ''
  File "/data/data/com.termux/files/home/sqlmap/lib/core/decorators.py", line 53, in _
    result = f(*args, **kwargs)
  File "/data/data/com.termux/files/home/sqlmap/lib/request/connect.py", line 1301, in queryPage
Traceback (most recent call last):
[01:45:02] [ERROR] thread 2: ''
File "/data/data/com.termux/files/home/sqlmap/lib/core/threads.py", line 93, in exceptionHandledFunction
    threadFunction()
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/sqlmap/lib/techniques/blind/inference.py", line 477, in blindThread
  File "/data/data/com.termux/files/home/sqlmap/lib/core/threads.py", line 93, in exceptionHandledFunction
    val = getChar(currentCharIndex, asciiTbl, not(charsetType is None and conf.charset))
    threadFunction()
[01:45:02] [ERROR] thread 4: ''
File "/data/data/com.termux/files/home/sqlmap/lib/techniques/blind/inference.py", line 477, in blindThread
Traceback (most recent call last):
    val = getChar(currentCharIndex, asciiTbl, not(charsetType is None and conf.charset))
  File "/data/data/com.termux/files/home/sqlmap/lib/techniques/blind/inference.py", line 339, in getChar
    result = Request.queryPage(forgedPayload, timeBasedCompare=timeBasedCompare, raise404=False)
  File "/data/data/com.termux/files/home/sqlmap/lib/core/decorators.py", line 53, in _
  File "/data/data/com.termux/files/home/sqlmap/lib/techniques/blind/inference.py", line 339, in getChar
    result = f(*args, **kwargs)
  File "/data/data/com.termux/files/home/sqlmap/lib/request/connect.py", line 1301, in queryPage
    result = Request.queryPage(forgedPayload, timeBasedCompare=timeBasedCompare, raise404=False)
  File "/data/data/com.termux/files/home/sqlmap/lib/core/decorators.py", line 53, in _
  File "/data/data/com.termux/files/home/sqlmap/lib/core/threads.py", line 93, in exceptionHandledFunction
    result = f(*args, **kwargs)
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "/data/data/com.termux/files/home/sqlmap/lib/request/connect.py", line 1301, in queryPage
    threadFunction()
  File "/data/data/com.termux/files/home/sqlmap/lib/request/connect.py", line 736, in getPage
  File "/data/data/com.termux/files/home/sqlmap/lib/techniques/blind/inference.py", line 477, in blindThread
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
    val = getChar(currentCharIndex, asciiTbl, not(charsetType is None and conf.charset))
  File "/data/data/com.termux/files/home/sqlmap/lib/request/connect.py", line 736, in getPage
  File "/data/data/com.termux/files/home/sqlmap/lib/techniques/blind/inference.py", line 339, in getChar
    raise SqlmapUserQuitException
    raise SqlmapUserQuitException
SqlmapUserQuitException
SqlmapUserQuitException
    result = Request.queryPage(forgedPayload, timeBasedCompare=timeBasedCompare, raise404=False)
  File "/data/data/com.termux/files/home/sqlmap/lib/core/decorators.py", line 53, in _
    result = f(*args, **kwargs)
  File "/data/data/com.termux/files/home/sqlmap/lib/request/connect.py", line 1301, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "/data/data/com.termux/files/home/sqlmap/lib/request/connect.py", line 736, in getPage
    raise SqlmapUserQuitException
SqlmapUserQuitException
    threadFunction()
  File "/data/data/com.termux/files/home/sqlmap/lib/techniques/blind/inference.py", line 477, in blindThread
    val = getChar(currentCharIndex, asciiTbl, not(charsetType is None and conf.charset))
  File "/data/data/com.termux/files/home/sqlmap/lib/techniques/blind/inference.py", line 339, in getChar
```
... (Are almost the same thing
and.. 
```
[01:45:02] [ERROR] thread 6: ''
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/sqlmap/lib/core/threads.py", line 93, in exceptionHandledFunction
    threadFunction()
  File "/data/data/com.termux/files/home/sqlmap/lib/techniques/blind/inference.py", line 477, in blindThread
    val = getChar(currentCharIndex, asciiTbl, not(charsetType is None and conf.charset))
  File "/data/data/com.termux/files/home/sqlmap/lib/techniques/blind/inference.py", line 339, in getChar
    result = Request.queryPage(forgedPayload, timeBasedCompare=timeBasedCompare, raise404=False)
  File "/data/data/com.termux/files/home/sqlmap/lib/core/decorators.py", line 53, in _
    result = f(*args, **kwargs)
  File "/data/data/com.termux/files/home/sqlmap/lib/request/connect.py", line 1301, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "/data/data/com.termux/files/home/sqlmap/lib/request/connect.py", line 736, in getPage
    raise SqlmapUserQuitException
SqlmapUserQuitException
    raise SqlmapUserQuitException
SqlmapUserQuitException
[01:45:03] [INFO] retrieved: None
[01:45:03] [DEBUG] performed 79 queries in 34.17 seconds

[*] ending @ 01:45:03 /2019-04-17/

sqlmap-shell>
```

**Comment by huitc** [comment]
(I did not enter the `ctrl+c`...

**Comment by stamparm** [comment]
Although traceback is being shown ONLY because you are using `-v` option, with the latest revision there should be no tracebacks in similar cases (when network unstable)

**Comment by huitc** [comment]
nice~
