### ISSUE TITLE
Traceback Exception

### ISSUE THREAD

**Issue by hack0mate** [sqlmapproject/sqlmap#3619]
```
 -u="***************" --tamper="overlongutf8more.py" --proxy="**********" --level=5 --risk=3 --text-only --headers="Content-Type: application/x-www-form-urlencoded" --method="POST" --is-dba -v 2 -f --banner --parse-errors -p "********"`
 
Traceback (most recent call last):
  File "sqlmap.py", line 412, in <module>
    main()
  File "sqlmap.py", line 348, in main
    errMsg = maskSensitiveData(errMsg)
  File "/root/sqlmap-dev/lib/core/common.py", line 3634, in maskSensitiveData
    regex = SENSITIVE_DATA_REGEX % re.sub(r"(\W)", r"\\\1", getUnicode(item))
  File "/usr/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
```

**Comment by hack0mate** [comment]
Traceback (most recent call last):
  File "/root/sqlmap-dev/lib/request/connect.py", line 420, in getPage
    value = re.sub(r"(%s)([^ \t])" % char, r"\g<1>\t\g<2>", value)
  File "/usr/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
