### ISSUE TITLE
SQLMap is hanging with tamper=randomcase enabled

### ISSUE THREAD

**Issue by mkauschi** [sqlmapproject/sqlmap#3634]
## What's the problem (or question)?
SQLMap is hanging at payload `Oracle AND error-based - WHERE or HAVING clause (UTL_INADDR.GET_HOST_ADDRESS)` with some URLs when using the tamper randomcase option. I found out about this when updating to Ubuntu 19.04 (SQLMap 1.3.4#stable). In Ubuntu 18.10 (I think SQLMap 1.2.10#stable) this problem did not occurre.

## How can we reproduce the issue?
The problem occurres with the following GET parameters:
`xml=<?xml version=\"1.0\" ?><creds><user>S\\xc3\\xbcleyman</user><pass>mypass</pass></creds>&Submit=Submit`

The problem can be reproduced with the following command:
`sqlmap --batch --flush-session --fresh-queries --purge --ignore-code=500 --ignore-code=400 --ignore-code=403 --timeout=100 --time-sec=10 --output-dir=./output --level=2 --risk=3 --method=get --url="http://example.com/index.php?xml=<?xml version=\"1.0\" ?><creds><user>S\\xc3\\xbcleyman</user><pass>mypass</pass></creds>&Submit=Submit" --answers=follow=N,skip=N,keep=Y,detect=Y,select=q,extending=Y --drop-set-cookie --ignore-redirects --retries=0 --tamper=randomcase`

(Replace example.com with an existing URL)

## What are the running context details?
Client OS: Ubuntu 19.04 & Arch Linux
Install method: apt-get & pacman
Program version: 1.3.4#stable 

Please let me know if you need any further information. 

Thanks & appreciate your hard work on this project

**Comment by stamparm** [comment]
I've found (without your provided data) one "problematic" case and patched it. Please pull the latest revision and retry

**Comment by huitc** [comment]
still cant...
```
[22:58:21] [DEBUG] running code integrity check
[22:58:21] [ERROR] wrong modification time of 'C:\Users\test\Documents\test\sql\tamper\randomcase.py'
[22:58:21] [CRITICAL] code integrity check failed (turning off automatic issue creation). You should retrieve the latest development version from official GitHub repository at 'https://github.com/sqlmapproject/sqlmap'

Traceback (most recent call last):
  File "sqlmap.py", line 179, in main
    start()
  File "C:\Users\test\Documents\test\sql\lib\core\decorators.py", line 71, in _
    result = f(*args, **kwargs)
  File "C:\Users\test\Documents\test\sql\lib\controller\controller.py", line 420, in start
    if not checkConnection(suppressOutput=conf.forms) or not checkString() or not checkRegexp():
  File "C:\Users\test\Documents\test\sql\lib\controller\checks.py", line 1589, in checkConnection
    Request.queryPage(content=True, noteResponseTime=False)
  File "C:\Users\test\Documents\test\sql\lib\core\decorators.py", line 71, in _
    result = f(*args, **kwargs)
  File "C:\Users\test\Documents\test\sql\lib\request\connect.py", line 1314, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "C:\Users\test\Documents\test\sql\lib\request\connect.py", line 500, in getPage
    conn = _urllib.request.urlopen(req)
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Users\test\Documents\test\sql\lib\request\httpshandler.py", line 100, in https_open
    return self.do_open(HTTPSConnection if ssl else _http_client.HTTPSConnection, req)
  File "C:\Python27\lib\urllib2.py", line 1195, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "C:\Python27\lib\httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "C:\Python27\lib\httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "C:\Python27\lib\httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 882, in _send_output
    self.send(msg)
  File "C:\Python27\lib\httplib.py", line 844, in send
    self.connect()
  File "C:\Users\test\Documents\test\sql\lib\request\httpshandler.py", line 56, in connect
    sock = create_sock()
  File "C:\Users\test\Documents\test\sql\lib\request\httpshandler.py", line 43, in create_sock
    sock = socket.create_connection((self.host, self.port), self.timeout)
  File "C:\Users\test\Documents\test\sql\lib\core\option.py", line 1006, in create_connection
    retVal = socket._create_connection(*args, **kwargs)
  File "C:\Users\test\Documents\test\sql\lib\core\option.py", line 1006, in create_connection
    retVal = socket._create_connection(*args, **kwargs)
  File "C:\Users\test\Documents\test\sql\lib\core\option.py", line 1006, in create_connection
    retVal = socket._create_connection(*args, **kwargs)
  File "C:\Users\test\Documents\test\sql\lib\core\option.py", line 1006, in create_connection
    retVal = socket._create_connection(*args, **kwargs)
  File "C:\Users\test\Documents\test\sql\lib\core\option.py", line 1006, in create_connection
    retVal = socket._create_connection(*args, **kwargs)
  File "C:\Users\test\Documents\test\sql\lib\core\option.py", line 1006, in create_connection
    retVal = socket._create_connection(*args, **kwargs)
  File "C:\Users\test\Documents\test\sql\lib\core\option.py", line 1006, in create_connection
    retVal = socket._create_connection(*args, **kwargs)
  File "C:\Users\test\Documents\test\sql\lib\core\option.py", line 1006, in create_connection
    retVal = socket._create_connection(*args, **kwargs)
  File "C:\Users\test\Documents\test\sql\lib\core\option.py", line 1006, in create_connection
    retVal = socket._create_connection(*args, **kwargs)
  File "C:\Users\test\Documents\test\sql\lib\core\option.py", line 1006, in create_connection
    retVal = socket._create_connection(*args, **kwargs)
  File "C:\Users\test\Documents\test\sql\lib\core\option.py", line 1006, in create_connection
    retVal = socket._create_connection(*args, **kwargs)
  File "C:\Users\test\Documents\test\sql\lib\core\option.py", line 1006, in create_connection
    retVal = socket._create_connection(*args, **kwargs)
  File "C:\Users\test\Documents\test\sql\lib\core\option.py", line 1006, in create_connection
    retVal = socket._create_connection(*args, **kwargs)
```

**Comment by mkauschi** [comment]
I can confirm the issue is fixed for me. Thanks a lot!
