### ISSUE TITLE
Windows multiprocessing hash cracking NotImplementedError

### ISSUE THREAD

**Issue by stamparm** [sqlmapproject/sqlmap#3766]
@huitc (https://github.com/sqlmapproject/sqlmap/issues/3762#issuecomment-502739315):

```
[INFO] starting 4 processes
Traceback (most recent call last):
  File "C:\Users\test\Documents\test\sqlmap\thirdparty\ansistrm\ansistrm.py", line 59, in emit
    message = stdoutEncode(self.format(record))
  File "C:\Users\test\Documents\test\sqlmap\thirdparty\ansistrm\ansistrm.py", line 24, in stdoutEncode
    raise NotImplementedError
NotImplementedError
Logged from file hash.py, line 811
Traceback (most recent call last):
  File "C:\Users\test\Documents\test\sqlmap\thirdparty\ansistrm\ansistrm.py", line 59, in emit
    message = stdoutEncode(self.format(record))
  File "C:\Users\test\Documents\test\sqlmap\thirdparty\ansistrm\ansistrm.py", line 24, in stdoutEncode
    raise NotImplementedError
NotImplementedError
Logged from file hash.py, line 811
```

**Comment by stamparm** [comment]
@huitc I am not able to reproduce on Win7/Python 2.7. Anything different at your side?

**Comment by stamparm** [comment]
@huitc unable to reproduce also with Win7/Python 3.7 (p.s. 4 processes)

**Comment by stamparm** [comment]
Pushed this moment a dirty patch which should solve this (unreproducible) bug
