### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by huitc** [sqlmapproject/sqlmap#3816]
```
python2 sqlmap.py -v 2 --null-connection --level 5 --risk 2 --predict-output --tor --delay 0.1 --time-sec 15 --sqlmap-shell --random-agent --drop-set-cookie --tamper randomcase,varnish,xforwardedfor,multiplespaces.py -u "https://www.test.us/test.php?id=1"

--hex --exclude-sysdbs --technique U -T test)_admin --common-files --batch

...
please enter number of threads? [Enter for 1 (current)] 1         [19:01:10] [INFO] tried 11/1122 items (1%)                        [19:01:13] [CRITICAL] connection dropped or unknown HTTP status code received. sqlmap is going to retry the request(s)
[19:32:05] [INFO] tried 444/1122 items (40%)                      Traceback (most recent call last):                                  File "/data/data/com.termux/files/home/sqlmap/lib/core/threads.py", line 146, in runThreads                                           threadFunction()
  File "/data/data/com.termux/files/home/sqlmap/lib/utils/brute.py", line 346, in fileExistsThread                                      result = unArrayizeValue(conf.dbmsHandler.readFile(path))       File "/data/data/com.termux/files/home/sqlmap/plugins/generic/filesystem.py", line 221, in readFile                                   fileContent = self.nonStackedReadFile(remoteFile)
  File "/data/data/com.termux/files/home/sqlmap/plugins/dbms/mysql/filesystem.py", line 31, in nonStackedReadFile                       result = inject.getValue("HEX(LOAD_FILE('%s'))" % rFile, charsetType=CHARSET_TYPE.HEXADECIMAL)                                    File "/data/data/com.termux/files/home/sqlmap/lib/core/decorators.py", line 71, in _
    result = f(*args, **kwargs)                                     File "/data/data/com.termux/files/home/sqlmap/lib/request/inject.py", line 411, in getValue                                           value = _goUnion(forgeCaseExpression if expected == EXPECTED.BOOL else query, unpack, dump)                                       File "/data/data/com.termux/files/home/sqlmap/lib/request/inject.py", line 347, in _goUnion                                           output = unionUse(expression, unpack=unpack, dump=dump)         File "/data/data/com.termux/files/home/sqlmap/lib/techniques/union/use.py", line 401, in unionUse                                     output = _oneShotUnionUse(expression, unpack)                   File "/data/data/com.termux/files/home/sqlmap/lib/techniques/union/use.py", line 90, in _oneShotUnionUse                              page, headers, _ = Request.queryPage(payload, content=True, raise404=False)                                                       File "/data/data/com.termux/files/home/sqlmap/lib/core/decorators.py", line 71, in _                                                  result = f(*args, **kwargs)
  File "/data/data/com.termux/files/home/sqlmap/lib/request/connect.py", line 1325, in queryPage                                        page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "/data/data/com.termux/files/home/sqlmap/lib/request/connect.py", line 511, in getPage                                           conn = _urllib.request.urlopen(req)                             File "/data/data/com.termux/files/usr/lib/python2.7/urllib2.py", line 154, in urlopen                                                 return opener.open(url, data, timeout)
  File "/data/data/com.termux/files/usr/lib/python2.7/urllib2.py", line 429, in open                                                    response = self._open(req, data)                                File "/data/data/com.termux/files/usr/lib/python2.7/urllib2.py", line 447, in _open                                                   '_open', req)                                                   File "/data/data/com.termux/files/usr/lib/python2.7/urllib2.py", line 407, in _call_chain                                             result = func(*args)                                            File "/data/data/com.termux/files/home/sqlmap/lib/request/httpshandler.py", line 100, in https_open                                   return self.do_open(HTTPSConnection if ssl else _http_client.HTTPSConnection, req)                                                File "/data/data/com.termux/files/usr/lib/python2.7/urllib2.py", line 1195, in do_open                                                h.request(req.get_method(), req.get_selector(), req.data, headers)                                                                File "/data/data/com.termux/files/usr/lib/python2.7/httplib.py", line 1042, in request                                                self._send_request(method, url, body, headers)                  File "/data/data/com.termux/files/usr/lib/python2.7/httplib.py", line 1012, in _send_request                                          self.endheaders(body)                                           File "/data/data/com.termux/files/usr/lib/python2.7/httplib.py", line 1031, in endheaders                                             self._send_output(message_body)
  File "/data/data/com.termux/files/usr/lib/python2.7/httplib.py", line 112, in _send_output                                            self.send(msg)                                                  File "/data/data/com.termux/files/usr/lib/python2.7/httplib.py", line 144, in send
    self.connect()                                                  File "/data/data/com.termux/files/home/sqlmap/lib/request/httpshandler.py", line 96, in connect                                       raise SqlmapConnectionException(errMsg)                       SqlmapConnectionException: can't establish SSL connection
                                                                  [19:32:01] [WARNING] no file(s) found                             [19:32:01] [INFO] fetched data logged to text files under '/data/data/com.termux/files/home/.sqlmap/output/www.test.us'   
[*] ending @ 19:32:01 /2019-07-10/

sqlmap-shell>
```

**Comment by stamparm** [comment]
p.s. you are forcing usage of non-default verbosity levels. Those traceback messages were meant to pinpoint the "problem" location (for developers) in high verbosity levels. Now turning it off for this kind of cases

**Comment by huitc** [comment]
ok... sorry😅
