### ISSUE TITLE
Traceback Exception

### ISSUE THREAD

**Issue by hack0mate** [sqlmapproject/sqlmap#3820]
Traceback (most recent call last):
  File "/root/sqlmap-dev/lib/core/threads.py", line 92, in exceptionHandledFunction
    threadFunction()
  File "/root/sqlmap-dev/lib/techniques/blind/inference.py", line 479, in blindThread
    val = getChar(currentCharIndex, asciiTbl, not(charsetType is None and conf.charset))
  File "/root/sqlmap-dev/lib/techniques/blind/inference.py", line 341, in getChar
    result = Request.queryPage(forgedPayload, timeBasedCompare=timeBasedCompare, raise404=False)
  File "/root/sqlmap-dev/lib/core/decorators.py", line 71, in _
    result = f(*args, **kwargs)
  File "/root/sqlmap-dev/lib/request/connect.py", line 1325, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "/root/sqlmap-dev/lib/request/connect.py", line 511, in getPage
    conn = _urllib.request.urlopen(req)
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/root/sqlmap-dev/lib/request/httpshandler.py", line 100, in https_open
    return self.do_open(HTTPSConnection if ssl else _http_client.HTTPSConnection, req)
  File "/usr/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/root/sqlmap-dev/lib/request/httpshandler.py", line 96, in connect
    raise SqlmapConnectionException(errMsg)
lib.core.exception.SqlmapConnectionException: can't establish SSL connection

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/root/sqlmap-dev/lib/core/threads.py", line 99, in exceptionHandledFunction
    errMsg = ex.message if isinstance(ex, SqlmapBaseException) else "%s: %s" % (type(ex).__name__, ex.message)
AttributeError: 'SqlmapConnectionException' object has no attribute 'message'

Exception in thread 3:
Traceback (most recent call last):
  File "/root/sqlmap-dev/lib/core/threads.py", line 92, in exceptionHandledFunction
    threadFunction()
  File "/root/sqlmap-dev/lib/techniques/blind/inference.py", line 479, in blindThread
    val = getChar(currentCharIndex, asciiTbl, not(charsetType is None and conf.charset))
  File "/root/sqlmap-dev/lib/techniques/blind/inference.py", line 341, in getChar
    result = Request.queryPage(forgedPayload, timeBasedCompare=timeBasedCompare, raise404=False)
  File "/root/sqlmap-dev/lib/core/decorators.py", line 71, in _
    result = f(*args, **kwargs)
  File "/root/sqlmap-dev/lib/request/connect.py", line 1325, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "/root/sqlmap-dev/lib/request/connect.py", line 511, in getPage
    conn = _urllib.request.urlopen(req)
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/root/sqlmap-dev/lib/request/httpshandler.py", line 100, in https_open
    return self.do_open(HTTPSConnection if ssl else _http_client.HTTPSConnection, req)
  File "/usr/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/root/sqlmap-dev/lib/request/httpshandler.py", line 96, in connect
    raise SqlmapConnectionException(errMsg)
lib.core.exception.SqlmapConnectionException: can't establish SSL connection

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/root/sqlmap-dev/lib/core/threads.py", line 99, in exceptionHandledFunction
    errMsg = ex.message if isinstance(ex, SqlmapBaseException) else "%s: %s" % (type(ex).__name__, ex.message)
AttributeError: 'SqlmapConnectionException' object has no attribute 'message'

Exception in thread 0:
Traceback (most recent call last):
  File "/root/sqlmap-dev/lib/core/threads.py", line 92, in exceptionHandledFunction
    threadFunction()
  File "/root/sqlmap-dev/lib/techniques/blind/inference.py", line 479, in blindThread
    val = getChar(currentCharIndex, asciiTbl, not(charsetType is None and conf.charset))
  File "/root/sqlmap-dev/lib/techniques/blind/inference.py", line 341, in getChar
    result = Request.queryPage(forgedPayload, timeBasedCompare=timeBasedCompare, raise404=False)
  File "/root/sqlmap-dev/lib/core/decorators.py", line 71, in _
    result = f(*args, **kwargs)
  File "/root/sqlmap-dev/lib/request/connect.py", line 1325, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "/root/sqlmap-dev/lib/request/connect.py", line 511, in getPage
    conn = _urllib.request.urlopen(req)
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/root/sqlmap-dev/lib/request/httpshandler.py", line 100, in https_open
    return self.do_open(HTTPSConnection if ssl else _http_client.HTTPSConnection, req)
  File "/usr/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/root/sqlmap-dev/lib/request/httpshandler.py", line 96, in connect
    raise SqlmapConnectionException(errMsg)
lib.core.exception.SqlmapConnectionException: can't establish SSL connection

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/root/sqlmap-dev/lib/core/threads.py", line 99, in exceptionHandledFunction
    errMsg = ex.message if isinstance(ex, SqlmapBaseException) else "%s: %s" % (type(ex).__name__, ex.message)
AttributeError: 'SqlmapConnectionException' object has no attribute 'message'

[05:33:40] [INFO] retrieved: __________ 22/42 (52%)Exception in thread 1:
Traceback (most recent call last):
  File "/root/sqlmap-dev/lib/core/threads.py", line 92, in exceptionHandledFunction
    threadFunction()
  File "/root/sqlmap-dev/lib/techniques/blind/inference.py", line 479, in blindThread
    val = getChar(currentCharIndex, asciiTbl, not(charsetType is None and conf.charset))
  File "/root/sqlmap-dev/lib/techniques/blind/inference.py", line 341, in getChar
    result = Request.queryPage(forgedPayload, timeBasedCompare=timeBasedCompare, raise404=False)
  File "/root/sqlmap-dev/lib/core/decorators.py", line 71, in _
    result = f(*args, **kwargs)
  File "/root/sqlmap-dev/lib/request/connect.py", line 1325, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "/root/sqlmap-dev/lib/request/connect.py", line 511, in getPage
    conn = _urllib.request.urlopen(req)
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/root/sqlmap-dev/lib/request/httpshandler.py", line 100, in https_open
    return self.do_open(HTTPSConnection if ssl else _http_client.HTTPSConnection, req)
  File "/usr/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/root/sqlmap-dev/lib/request/httpshandler.py", line 96, in connect
    raise SqlmapConnectionException(errMsg)
lib.core.exception.SqlmapConnectionException: can't establish SSL connection

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/root/sqlmap-dev/lib/core/threads.py", line 99, in exceptionHandledFunction
    errMsg = ex.message if isinstance(ex, SqlmapBaseException) else "%s: %s" % (type(ex).__name__, ex.message)
AttributeError: 'SqlmapConnectionException' object has no attribute 'message'

Exception in thread 9:
Traceback (most recent call last):
  File "/root/sqlmap-dev/lib/core/threads.py", line 92, in exceptionHandledFunction
    threadFunction()
  File "/root/sqlmap-dev/lib/techniques/blind/inference.py", line 479, in blindThread
    val = getChar(currentCharIndex, asciiTbl, not(charsetType is None and conf.charset))
  File "/root/sqlmap-dev/lib/techniques/blind/inference.py", line 341, in getChar
    result = Request.queryPage(forgedPayload, timeBasedCompare=timeBasedCompare, raise404=False)
  File "/root/sqlmap-dev/lib/core/decorators.py", line 71, in _
    result = f(*args, **kwargs)
  File "/root/sqlmap-dev/lib/request/connect.py", line 1325, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "/root/sqlmap-dev/lib/request/connect.py", line 511, in getPage
    conn = _urllib.request.urlopen(req)
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/root/sqlmap-dev/lib/request/httpshandler.py", line 100, in https_open
    return self.do_open(HTTPSConnection if ssl else _http_client.HTTPSConnection, req)
  File "/usr/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/root/sqlmap-dev/lib/request/httpshandler.py", line 96, in connect
    raise SqlmapConnectionException(errMsg)
lib.core.exception.SqlmapConnectionException: can't establish SSL connection

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/root/sqlmap-dev/lib/core/threads.py", line 99, in exceptionHandledFunction
    errMsg = ex.message if isinstance(ex, SqlmapBaseException) else "%s: %s" % (type(ex).__name__, ex.message)
AttributeError: 'SqlmapConnectionException' object has no attribute 'message'

Exception in thread 4:
Traceback (most recent call last):
  File "/root/sqlmap-dev/lib/core/threads.py", line 92, in exceptionHandledFunction
    threadFunction()
  File "/root/sqlmap-dev/lib/techniques/blind/inference.py", line 479, in blindThread
    val = getChar(currentCharIndex, asciiTbl, not(charsetType is None and conf.charset))
  File "/root/sqlmap-dev/lib/techniques/blind/inference.py", line 341, in getChar
    result = Request.queryPage(forgedPayload, timeBasedCompare=timeBasedCompare, raise404=False)
  File "/root/sqlmap-dev/lib/core/decorators.py", line 71, in _
    result = f(*args, **kwargs)
  File "/root/sqlmap-dev/lib/request/connect.py", line 1325, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "/root/sqlmap-dev/lib/request/connect.py", line 511, in getPage
    conn = _urllib.request.urlopen(req)
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/root/sqlmap-dev/lib/request/httpshandler.py", line 100, in https_open
    return self.do_open(HTTPSConnection if ssl else _http_client.HTTPSConnection, req)
  File "/usr/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/root/sqlmap-dev/lib/request/httpshandler.py", line 96, in connect
    raise SqlmapConnectionException(errMsg)
lib.core.exception.SqlmapConnectionException: can't establish SSL connection

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/root/sqlmap-dev/lib/core/threads.py", line 99, in exceptionHandledFunction
    errMsg = ex.message if isinstance(ex, SqlmapBaseException) else "%s: %s" % (type(ex).__name__, ex.message)
AttributeError: 'SqlmapConnectionException' object has no attribute 'message'

Exception in thread 8:
Traceback (most recent call last):
  File "/root/sqlmap-dev/lib/core/threads.py", line 92, in exceptionHandledFunction
    threadFunction()
  File "/root/sqlmap-dev/lib/techniques/blind/inference.py", line 479, in blindThread
    val = getChar(currentCharIndex, asciiTbl, not(charsetType is None and conf.charset))
  File "/root/sqlmap-dev/lib/techniques/blind/inference.py", line 341, in getChar
    result = Request.queryPage(forgedPayload, timeBasedCompare=timeBasedCompare, raise404=False)
  File "/root/sqlmap-dev/lib/core/decorators.py", line 71, in _
    result = f(*args, **kwargs)
  File "/root/sqlmap-dev/lib/request/connect.py", line 1325, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "/root/sqlmap-dev/lib/request/connect.py", line 511, in getPage
    conn = _urllib.request.urlopen(req)
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/root/sqlmap-dev/lib/request/httpshandler.py", line 100, in https_open
    return self.do_open(HTTPSConnection if ssl else _http_client.HTTPSConnection, req)
  File "/usr/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/root/sqlmap-dev/lib/request/httpshandler.py", line 96, in connect
    raise SqlmapConnectionException(errMsg)
lib.core.exception.SqlmapConnectionException: can't establish SSL connection

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/root/sqlmap-dev/lib/core/threads.py", line 99, in exceptionHandledFunction
    errMsg = ex.message if isinstance(ex, SqlmapBaseException) else "%s: %s" % (type(ex).__name__, ex.message)
AttributeError: 'SqlmapConnectionException' object has no attribute 'message'

**Comment by stamparm** [comment]
@hack0mate thx
