### ISSUE TITLE
Ive been getting this lately while testing a site. It says I should report it so thats why I opened a new issue!

### ISSUE THREAD

**Issue by its0x08** [sqlmapproject/sqlmap#3924]
`[09:20:47] [ERROR] thread MainThread: unhandled exception occurred in sqlmap/1.3.9.11#dev. It is recommended to retry your run with the latest development version from official GitHub repository at 'https://githu>
Running version: 1.3.9.11#dev
Python version: 3.7.4+
Operating system: Linux-5.2.0-kali2-amd64-x86_64-with-Kali-kali-rolling-kali-rolling
Command line: sqlmap.py --url=[red] --forms --batch --random-agent --threads 5 --crawl=1 --dbms=mssql
Technique: None
Back-end DBMS: Microsoft SQL Server (identified)
Traceback (most recent call last):
  File "/scripts/sqlmap/thirdparty/beautifulsoup/beautifulsoup.py", line 897, in recursiveChildGenerator
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scripts/sqlmap/lib/core/threads.py", line 149, in runThreads
    threadFunction()
  File "/scripts/sqlmap/lib/utils/crawler.py", line 92, in crawlThread
    soup = BeautifulSoup(content)
  File "/scripts/sqlmap/thirdparty/beautifulsoup/beautifulsoup.py", line 1539, in __init__
    BeautifulStoneSoup.__init__(self, *args, **kwargs)
  File "/scripts/sqlmap/thirdparty/beautifulsoup/beautifulsoup.py", line 1164, in __init__
    self._feed(isHTML=isHTML)
  File "/scripts/sqlmap/thirdparty/beautifulsoup/beautifulsoup.py", line 1183, in _feed
    if not hasattr(self, 'originalEncoding'):
  File "/scripts/sqlmap/thirdparty/beautifulsoup/beautifulsoup.py", line 1221, in __getattr__
    return Tag.__getattr__(self, methodName)
  File "/scripts/sqlmap/thirdparty/beautifulsoup/beautifulsoup.py", line 682, in __getattr__
    return self.find(tag)
  File "/scripts/sqlmap/thirdparty/beautifulsoup/beautifulsoup.py", line 846, in find
    l = self.findAll(name, attrs, recursive, text, 1, **kwargs)
  File "/scripts/sqlmap/thirdparty/beautifulsoup/beautifulsoup.py", line 866, in findAll
    return self._findAll(name, attrs, text, limit, generator, **kwargs)
  File "/scripts/sqlmap/thirdparty/beautifulsoup/beautifulsoup.py", line 392, in _findAll
    i = next(g)
RuntimeError: generator raised StopIteration
`

**Comment by stamparm** [comment]
PEP 479 enforced from Python 3.7 (aka Python3 should burn)
