### ISSUE TITLE
error when usage of --dns-domain

### ISSUE THREAD

**Issue by caperoni** [sqlmapproject/sqlmap#4080]
```
ck (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/sqlmap/lib/request/dns.py", line 119, in _
    _ = DNSQuery(data)
  File "/root/sqlmap/lib/request/dns.py", line 31, in __init__
    type_ = (ord(raw[2]) >> 3) & 15                 # Opcode bits
TypeError: ord() expected string of length 1, but int found
```

**Comment by caperoni** [comment]
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/sqlmap/lib/request/dns.py", line 119, in _
    _ = DNSQuery(data)
  File "/root/sqlmap/lib/request/dns.py", line 31, in __init__
    type_ = (ord(raw[2]) >> 3) & 15                 # Opcode bits
TypeError: ord() expected string of length 1, but int found
```
