### ISSUE TITLE
cheak time based mysql may lead to codecs problems

### ISSUE THREAD

**Issue by a59921268** [sqlmapproject/sqlmap#4209]
`

python2 sqlmap.py -u "192.168.111.46:8546/Less-8/" --technique T  --dbs
caused the problem:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 9: ordinal not in range(128)
`

**Comment by stamparm** [comment]
I would need the whole error traceback (thing you get with sqlmap in case of error - colored in red), as this kind of errors are untraceable without any kind of additional information

**Comment by a59921268** [comment]
thank you,
`
D:\toolssqlmap-py>python2 sqlmap.py -u "ipadd/Less-8/" --technique T  --dbs

    sqlmap/0.9 - automatic SQL injection and database takeover tool
    http://sqlmap.sourceforge.net

[*] starting at: 22:17:25


[22:17:25] [CRITICAL] unhandled exception in sqlmap/0.9, retry your run with the latest development version from the Subversion repository. If the exception persists, please send by e-mail to sqlmap-users@lists.sourceforge.net the following text and any information required to reproduce the bug. The developers will try to reproduce the bug, fix it accordingly and get back to you.
sqlmap version: 0.9 (r3630)
Python version: 2.7.18
Operating system: nt
Command line: sqlmap.py -u ************************* --technique T --dbs
Technique: None
Back-end DBMS: None (identified)
Traceback (most recent call last):
  File "sqlmap.py", line 82, in main
    start()
  File "D:\tools\sqlmap-py\lib\controller\controller.py", line 267, in start
    setupTargetEnv()
  File "D:\tools\sqlmap-py\lib\core\target.py", line 313, in setupTargetEnv
    __createTargetDirs()
  File "D:\tools\sqlmap-py\lib\core\target.py", line 265, in __createTargetDirs
    conf.outputPath = "%s%s%s" % (paths.SQLMAP_OUTPUT_PATH, os.sep, conf.hostname)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 9: ordinal not in range(128)

[*] shutting down at: 22:17:25
`

**Comment by stamparm** [comment]
Not sure if you are trolling, but you are posting here a bug for a version of sqlmap which is 6 years old. This line of code has been changed 6 years ago.
