### ISSUE TITLE
Fix handling of exit in thirdparty library "identYwaf"

### ISSUE THREAD

**Issue by dhaug-op** [sqlmapproject/sqlmap#4227]
**Describe the bug**
The currently included version of "identYwaf" contains a bug preventing the use with embeddable python (see https://github.com/stamparm/identYwaf/pull/12).

**To Reproduce**
1. Download (https://www.python.org/ftp/python/3.8.2/python-3.8.2-embed-amd64.zip) and unzip embeddable Python and install sqlmap into its folder with systems python ``pip`` (``pip install --target path-to-embeddable-python\ sqlmap``)
1. Run `path-to-embeddable-python\python.exe -m sqlmap.sqlmap -h`
2. See error:

```
Traceback (most recent call last):
  File "runpy.py", line 193, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "<path-to-embeddable-python>\sqlmap\sqlmap.py", line 72, in <module>
    from lib.core.option import init
  File "<path-to-embeddable-python>\sqlmap\lib\core\option.py", line 24, in <module>
    from lib.controller.checks import checkConnection
  File "<path-to-embeddable-python>\sqlmap\lib\controller\checks.py", line 102, in <module>
    from lib.request.connect import Connect as Request
  File "<path-to-embeddable-python>\sqlmap\lib\request\connect.py", line 123, in <module>
    from lib.request.basic import decodePage
  File "<path-to-embeddable-python>\sqlmap\lib\request\basic.py", line 57, in <module>
    from thirdparty.identywaf import identYwaf
  File "<path-to-embeddable-python>\sqlmap\thirdparty\identywaf\identYwaf.py", line 128, in <module>
    _exit = exit
NameError: name 'exit' is not defined
```

**Expected behavior**
SQLmap should work normally with embeddable python.

**Running environment:**
 - sqlmap version: 1.4.6
 - Installation method: pip
 - Operating system: Microsoft Windows 10
 - Python version: embeddable Python (https://docs.python.org/3/using/windows.html#the-embeddable-package) 3.8.2 (https://www.python.org/ftp/python/3.8.2/python-3.8.2-embed-amd64.zip)

**Additional context**
The library ``identYwaf`` was fixed with https://github.com/stamparm/identYwaf/pull/12, further reasoning for the issue is given there. Updating to the newest version should fix this issue.

**Comment by dhaug-op** [comment]
Thanks very much for the quick response and fix! Great work!
