### ISSUE TITLE
unhandled exception, resetCookieJar

### ISSUE THREAD

**Issue by mide22** [sqlmapproject/sqlmap#4451]
```
[ERROR] thread MainThread: unhandled exception occurred in sqlmap/1.4.12.3#dev. It is recommended to retry your run with the latest development version from official GitHub repository at 'https://github.com/sqlmapproject/sqlmap'. If the exception persists, please open a new issue at 'https://github.com/sqlmapproject/sqlmap/issues/new' with the following text and any other information required to reproduce the bug. Developers will try to reproduce the bug, fix it accordingly and get back to you
Running version: 1.4.12.3#dev
Python version: 3.6.8
Operating system: Linux-3.10.0-957.10.1.el7.x86_64-x86_64-with-centos-8.2.2004-Core
Command line: sqlmap.py --level=1 --risk=1 --dbms=mysql --batch -m /data/loggedInUrls.list --load-cookies=/data/loggedIn.cookies --output-dir=/data/sqlmapResults -o --crawl=1 --forms --crawl-exclude=(log-in|log-out|search) -v 4
Technique: TIME
Back-end DBMS: MySQL (fingerprinted)
Traceback (most recent call last):
  File "/sqlmap-dev/lib/core/common.py", line 4992, in resetCookieJar
    if cookie.expires < time.time():
TypeError: '<' not supported between instances of 'NoneType' and 'float'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sqlmap-dev/lib/core/threads.py", line 156, in runThreads
    threadFunction()
  File "/sqlmap-dev/lib/utils/crawler.py", line 75, in crawlThread
    content = Request.getPage(url=current, post=post, cookie=None, crawling=True, raise404=False)[0]
  File "/sqlmap-dev/lib/request/connect.py", line 412, in getPage
    headers = forgeHeaders({HTTP_HEADER.COOKIE: cookie, HTTP_HEADER.USER_AGENT: ua, HTTP_HEADER.REFERER: referer, HTTP_HEADER.HOST: host}, base=None if target else {})
  File "/sqlmap-dev/lib/core/decorators.py", line 94, in _
    result = f(*args, **kwargs)
  File "/sqlmap-dev/lib/request/basic.py", line 138, in forgeHeaders
    resetCookieJar(conf.cj)
  File "/sqlmap-dev/lib/core/common.py", line 5005, in resetCookieJar
    raise SqlmapGenericException(errMsg)

```

Cookie-File:
```
# HTTP cookie file.
# Generated by Wget on 2020-12-02 13:54:00.
# Edit at your own risk.

.project.trunk.dev.local	TRUE	/	FALSE	1638453240	auth-project	1821793%3Acd757eb69a6e2fd4b72f0c8b5e5473c8
.project.trunk.dev.local	TRUE	/	FALSE	0	currentLocale	de_DE
.project.trunk.dev.local	TRUE	/	FALSE	1608126840	user	d41d8cd98f00b204e9800998ecf8427e

```

PS, if've got a similar error without trace by using crawl=2 and given cookie list:
`[ERROR] there was a problem loading cookies file ('TypeError: '<' not supported between instances of 'NoneType' and 'float''), skipping to the next URL
`

Thanks for your work!

**Comment by stamparm** [comment]
Strange, I am not able to reproduce this with your own provided cookie file. Anyhow, "patched" this with the latest revision
