### ISSUE TITLE
bug!

### ISSUE THREAD

**Issue by c2xusnpq6** [sqlmapproject/sqlmap#4576]
I've encountered the same situation earlier but other server

```
[13:22:47] [INFO] testing connection to the target URL

[13:22:47] [DEBUG] running code integrity check
[13:22:48] [CRITICAL] unhandled exception occurred in sqlmap/1.5.2.12#dev. It is recommended to retry your run with the latest development version from official GitHub repository at 'https://github.com/sqlmapproject/sqlmap'. If the exception persists, please open a new issue at 'https://github.com/sqlmapproject/sqlmap/issues/new' with the following text and any other information required to reproduce the bug. Developers will try to reproduce the bug, fix it accordingly and get back to you
Running version: 1.5.2.12#dev
Python version: 3.9.1
Operating system: Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.31
Command line: sqlmap.py -v 2 --tor -u ****************************************************************** --data ******************************************************************************************************************************** --level 5 --risk 3 --time-sec 15 --retries 5 --unstable --keep-alive --sqlmap-shell --random-agent --drop-set-cookie -p txtEmpNo --chunk --tamper sp_password,charunicodeencode.py,luanginx.py
Technique: None
Back-end DBMS: None

[*] ending @ 13:22:48 /2021-02-10/
```

**Comment by c2xusnpq6** [comment]
```
Traceback (most recent call last):
  File "/mnt/c/Users/test/test/sqlmap/sqlmap.py", line 217, in main
    start()
  File "/mnt/c/Users/test/test/sqlmap/lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "/mnt/c/Users/test/test/sqlmap/lib/controller/controller.py", line 437, in start
    if not checkConnection(suppressOutput=conf.forms) or not checkString() or not checkRegexp():
  File "/mnt/c/Users/test/test/sqlmap/lib/controller/checks.py", line 1545, in checkConnection
    Request.queryPage(content=True, noteResponseTime=False)
  File "/mnt/c/Users/test/test/sqlmap/lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "/mnt/c/Users/test/test/sqlmap/lib/request/connect.py", line 1436, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "/mnt/c/Users/test/test/sqlmap/lib/request/connect.py", line 599, in getPage
    conn = _urllib.request.urlopen(req)
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/usr/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 1371, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.9/urllib/request.py", line 1342, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1296, in _send_request
    self.putheader(hdr, value)
  File "/mnt/c/Users/test/test/sqlmap/lib/core/option.py", line 2485, in putheader
    self._putheader(header, *values)
  File "/mnt/c/Users/test/test/sqlmap/lib/core/option.py", line 2485, in putheader
    self._putheader(header, *values)
  File "/mnt/c/Users/test/test/sqlmap/lib/core/option.py", line 2485, in putheader
    self._putheader(header, *values)
  [Previous line repeated 979 more times]
  File "/mnt/c/Users/test/test/sqlmap/lib/core/option.py", line 2484, in putheader
    if header != HTTP_HEADER.CONTENT_LENGTH:
RecursionError: maximum recursion depth exceeded in comparison

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/test/test/sqlmap/sqlmap.py", line 480, in main
    dataToStdout("%s\n" % setColor(excMsg.strip(), level=logging.CRITICAL))
  File "/mnt/c/Users/test/test/sqlmap/lib/core/common.py", line 977, in setColor
    retVal = LOGGER_HANDLER.colorize(message, level, True)
  File "/mnt/c/Users/test/test/sqlmap/lib/core/log.py", line 27, in colorize
    bg, fg, bold = self.level_map[levelno]
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/test/test/sqlmap/sqlmap.py", line 217, in main
    start()
  File "/mnt/c/Users/test/test/sqlmap/lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "/mnt/c/Users/test/test/sqlmap/lib/controller/controller.py", line 437, in start
    if not checkConnection(suppressOutput=conf.forms) or not checkString() or not checkRegexp():
  File "/mnt/c/Users/test/test/sqlmap/lib/controller/checks.py", line 1545, in checkConnection
    Request.queryPage(content=True, noteResponseTime=False)
  File "/mnt/c/Users/test/test/sqlmap/lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "/mnt/c/Users/test/test/sqlmap/lib/request/connect.py", line 1436, in queryPage
    page, headers, code = Connect.getPage(url=uri, get=get, post=post, method=method, cookie=cookie, ua=ua, referer=referer, host=host, silent=silent, auxHeaders=auxHeaders, response=response, raise404=raise404, ignoreTimeout=timeBasedCompare)
  File "/mnt/c/Users/test/test/sqlmap/lib/request/connect.py", line 599, in getPage
    conn = _urllib.request.urlopen(req)
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/usr/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 1371, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.9/urllib/request.py", line 1342, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1296, in _send_request
    self.putheader(hdr, value)
  File "/mnt/c/Users/test/test/sqlmap/lib/core/option.py", line 2485, in putheader
    self._putheader(header, *values)
  File "/mnt/c/Users/test/test/sqlmap/lib/core/option.py", line 2485, in putheader
    self._putheader(header, *values)
  File "/mnt/c/Users/test/test/sqlmap/lib/core/option.py", line 2485, in putheader
    self._putheader(header, *values)
  [Previous line repeated 977 more times]
  File "/mnt/c/Users/test/test/sqlmap/lib/core/option.py", line 2484, in putheader
    if header != HTTP_HEADER.CONTENT_LENGTH:
RecursionError: maximum recursion depth exceeded in comparison

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/test/test/sqlmap/sqlmap.py", line 540, in <module>
    main()
  File "/mnt/c/Users/test/test/sqlmap/sqlmap.py", line 536, in main
    main()
  File "/mnt/c/Users/test/test/sqlmap/sqlmap.py", line 536, in main
    main()
  File "/mnt/c/Users/test/test/sqlmap/sqlmap.py", line 536, in main
    main()
  File "/mnt/c/Users/test/test/sqlmap/sqlmap.py", line 480, in main
    dataToStdout("%s\n" % setColor(excMsg.strip(), level=logging.CRITICAL))
  File "/mnt/c/Users/test/test/sqlmap/lib/core/common.py", line 977, in setColor
    retVal = LOGGER_HANDLER.colorize(message, level, True)
  File "/mnt/c/Users/test/test/sqlmap/lib/core/log.py", line 27, in colorize
    bg, fg, bold = self.level_map[levelno]
KeyError: None
```

**Comment by c2xusnpq6** [comment]
The latest two versions have the same problem
