### ISSUE TITLE
dependencies problem?

### ISSUE THREAD

**Issue by c2xusnpq6** [sqlmapproject/sqlmap#4601]
```
# python3 sqlmap.py -v 2 --gui
        ___
       __H__
 ___ ___[,]_____ ___ ___  {1.5.3.2#dev}
|_ -| . [,]     | .'| . |
|___|_  [.]_|_|_|__,|  _|
      |_|V...       |_|   http://sqlmap.org


[17:36:32] [CRITICAL] unhandled exception occurred in sqlmap/1.5.3.2#dev. It is recommended to retry your run with the latest development version from official GitHub repository at 'https://github.com/sqlmapproject/sqlmap'. If the exception persists, please open a new issue at 'https://github.com/sqlmapproject/sqlmap/issues/new' with the following text and any other information required to reproduce the bug. Developers will try to reproduce the bug, fix it accordingly and get back to you
Running version: 1.5.3.2#dev
Python version: 3.9.1+
Operating system: Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.31
Command line: sqlmap.py -v 2 --gui
Technique: None
Back-end DBMS: None
Traceback (most recent call last):
  File "sqlmap.py", line 146, in main
    args = cmdLineParser()
  File "lib/parse/cmdline.py", line 899, in cmdLineParser
    runGui(parser)
  File "lib/core/gui.py", line 75, in runGui
    window = _tkinter.Tk()
  File "/usr/lib/python3.9/tkinter/__init__.py", line 2262, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
```

**Comment by c2xusnpq6** [comment]
`Linux DESKTOP-FreEhk0Ng 4.4.0-19041-Microsoft #488-Microsoft Mon Sep 01 13:43:00 PST 2020 x86_64 GNU/Linux`
`wsl1 kali `

**Comment by stamparm** [comment]
https://stackoverflow.com/a/48304920
