### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by c2xusnpq6** [sqlmapproject/sqlmap#4607]
```
[15:54:42] [INFO] sqlmap will dump entries of all tables from all databases now
[15:54:42] [INFO] fetching database names
[15:54:50] [DEBUG] got HTTP error code: 500 ('Internal Server Error')
[15:54:50] [DEBUG] retrying failed SQL query without the ORDER BY clause
[15:54:50] [ERROR] thread 3: 'KeyError: 6'
Traceback (most recent call last):
  File "/mnt/c/Users/user/sqlmap/lib/core/threads.py", line 97, in exceptionHandledFunction
    threadFunction()
  File "/mnt/c/Users/user/sqlmap/lib/techniques/union/use.py", line 357, in unionThread
    output = _oneShotUnionUse(limitedExpr, unpack, True)
  File "/mnt/c/Users/user/sqlmap/lib/techniques/union/use.py", line 168, in _oneShotUnionUse
    retVal = _oneShotUnionUse(expression, unpack, limited)
  File "/mnt/c/Users/user/sqlmap/lib/techniques/union/use.py", line 177, in _oneShotUnionUse
    vector = kb.injection.data[PAYLOAD.TECHNIQUE.UNION].vector
KeyError: 6
[15:55:00] [DEBUG] got HTTP error code: 500 ('Internal Server Error')
[15:55:00] [ERROR] thread 9: 'KeyError: 6'
Traceback (most recent call last):
  File "/mnt/c/Users/user/sqlmap/lib/core/threads.py", line 97, in exceptionHandledFunction
    threadFunction()
  File "/mnt/c/Users/user/sqlmap/lib/techniques/union/use.py", line 357, in unionThread
    output = _oneShotUnionUse(limitedExpr, unpack, True)
  File "/mnt/c/Users/user/sqlmap/lib/techniques/union/use.py", line 168, in _oneShotUnionUse
    retVal = _oneShotUnionUse(expression, unpack, limited)
  File "/mnt/c/Users/user/sqlmap/lib/techniques/union/use.py", line 177, in _oneShotUnionUse
    vector = kb.injection.data[PAYLOAD.TECHNIQUE.UNION].vector
KeyError: 6
[15:55:06] [CRITICAL] connection timed out to the target URL
[15:55:06] [ERROR] thread 7: 'KeyError: 6'
Traceback (most recent call last):
  File "/mnt/c/Users/user/sqlmap/lib/core/threads.py", line 97, in exceptionHandledFunction
    threadFunction()
  File "/mnt/c/Users/user/sqlmap/lib/techniques/union/use.py", line 357, in unionThread
    output = _oneShotUnionUse(limitedExpr, unpack, True)
  File "/mnt/c/Users/user/sqlmap/lib/techniques/union/use.py", line 168, in _oneShotUnionUse
    retVal = _oneShotUnionUse(expression, unpack, limited)
  File "/mnt/c/Users/user/sqlmap/lib/techniques/union/use.py", line 177, in _oneShotUnionUse
    vector = kb.injection.data[PAYLOAD.TECHNIQUE.UNION].vector
KeyError: 6
[15:55:12] [CRITICAL] connection timed out to the target URL
[15:55:12] [ERROR] thread 4: 'KeyError: 6'
Traceback (most recent call last):
  File "/mnt/c/Users/user/sqlmap/lib/core/threads.py", line 97, in exceptionHandledFunction
    threadFunction()
  File "/mnt/c/Users/user/sqlmap/lib/techniques/union/use.py", line 357, in unionThread
    output = _oneShotUnionUse(limitedExpr, unpack, True)
  File "/mnt/c/Users/user/sqlmap/lib/techniques/union/use.py", line 168, in _oneShotUnionUse
    retVal = _oneShotUnionUse(expression, unpack, limited)
  File "/mnt/c/Users/user/sqlmap/lib/techniques/union/use.py", line 177, in _oneShotUnionUse
    vector = kb.injection.data[PAYLOAD.TECHNIQUE.UNION].vector
KeyError: 6
[15:55:18] [DEBUG] connection timed out to the target URL. sqlmap is going to retry the request
[15:55:18] [WARNING] if the problem persists please try to lower the number of used threads (option '--threads')
[15:55:25] [CRITICAL] connection timed out to the target URL
[15:55:25] [ERROR] thread 6: 'KeyError: 6'
Traceback (most recent call last):
  File "/mnt/c/Users/user/sqlmap/lib/core/threads.py", line 97, in exceptionHandledFunction
    threadFunction()
  File "/mnt/c/Users/user/sqlmap/lib/techniques/union/use.py", line 357, in unionThread
    output = _oneShotUnionUse(limitedExpr, unpack, True)
  File "/mnt/c/Users/user/sqlmap/lib/techniques/union/use.py", line 168, in _oneShotUnionUse
    retVal = _oneShotUnionUse(expression, unpack, limited)
  File "/mnt/c/Users/user/sqlmap/lib/techniques/union/use.py", line 177, in _oneShotUnionUse
    vector = kb.injection.data[PAYLOAD.TECHNIQUE.UNION].vector
KeyError: 6
[15:55:31] [DEBUG] connection timed out to the target URL. sqlmap is going to retry the request
[15:55:36] [DEBUG] connection timed out to the target URL. sqlmap is going to retry the request
[15:55:41] [DEBUG] connection timed out to the target URL. sqlmap is going to retry the request
[15:55:42] [CRITICAL] connection timed out to the target URL. sqlmap is going to retry the request(s)
[15:55:54] [DEBUG] got HTTP error code: 500 ('Internal Server Error')
[15:55:54] [ERROR] thread 8: 'KeyError: 6'
Traceback (most recent call last):
  File "/mnt/c/Users/user/sqlmap/lib/core/threads.py", line 97, in exceptionHandledFunction
    threadFunction()
  File "/mnt/c/Users/user/sqlmap/lib/techniques/union/use.py", line 357, in unionThread
    output = _oneShotUnionUse(limitedExpr, unpack, True)
  File "/mnt/c/Users/user/sqlmap/lib/techniques/union/use.py", line 168, in _oneShotUnionUse
    retVal = _oneShotUnionUse(expression, unpack, limited)
  File "/mnt/c/Users/user/sqlmap/lib/techniques/union/use.py", line 177, in _oneShotUnionUse
    vector = kb.injection.data[PAYLOAD.TECHNIQUE.UNION].vector
KeyError: 6
```

**Comment by c2xusnpq6** [comment]
Tell me if you need more detail

**Comment by stamparm** [comment]
Is this reproducible if you rerun everything with `--flush-session`?

**Comment by c2xusnpq6** [comment]
yes

**Comment by c2xusnpq6** [comment]
in that time, my network is very unstable (tor problem?

**Comment by c2xusnpq6** [comment]
im sorry, it's *without* tor or any kind of proxy

**Comment by c2xusnpq6** [comment]
server problem i think

**Comment by c2xusnpq6** [comment]
it's --> `--threads 10 --technique U --cookie xxx=xxx` 

`--cookie` problem?

**Comment by stamparm** [comment]
@c2xusnpq6 if you provide me with all the details (privately) and I reproduce it, I'll be able to fix it. currently not able to do it

**Comment by c2xusnpq6** [comment]
maybe next time ^^''

**Comment by c2xusnpq6** [comment]
sorry~ ^^''
