### ISSUE TITLE
Unhandled Exception: BrokenPipeError: [Errno 32] Broken pipe when running sqlmap

### ISSUE THREAD

**Issue by mai1x9** [sqlmapproject/sqlmap#5255]
**Describe the bug**
In very rare cases, sometimes handled exception is raised. as shown below, the error stack,
```
Traceback (most recent call last):
  File "sqlmap.py", line 222, in main
    start()
  File "/home/lns_vm05/Desktop/sqlinjection/sqlmap/lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "/home/lns_vm05/Desktop/sqlinjection/sqlmap/lib/controller/controller.py", line 590, in start
    injection = checkSqlInjection(place, parameter, value)
  File "/home/lns_vm05/Desktop/sqlinjection/sqlmap/lib/controller/checks.py", line 662, in checkSqlInjection
    trueResult = Request.queryPage(reqPayload, place, timeBasedCompare=True, raise404=False)
  File "/home/lns_vm05/Desktop/sqlinjection/sqlmap/lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "/home/lns_vm05/Desktop/sqlinjection/sqlmap/lib/request/connect.py", line 1470, in queryPage
    dataToStdout('.')
  File "/home/lns_vm05/Desktop/sqlinjection/sqlmap/lib/core/common.py", line 1037, in dataToStdout
    sys.stdout.flush()
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sqlmap.py", line 440, in main
    raise SystemExit
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sqlmap.py", line 593, in <module>
    main()
  File "sqlmap.py", line 543, in main
    dataToStdout("\n[*] ending @ %s\n\n" % time.strftime("%X /%Y-%m-%d/"), forceOutput=True)
  File "/home/lns_vm05/Desktop/sqlinjection/sqlmap/lib/core/common.py", line 1037, in dataToStdout
    sys.stdout.flush()
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
```
**To Reproduce**
- The issue occurs only in some rare cases, if the command is re-run it works again perfectly fine.

**Running environment:**
 - sqlmap version: 1.6.12
 - Installation method Git clone into current directory and running `sqlmap.py` directly
 - Operating system: Ubuntu 16.04
 - Python version: 3.6.9

**Target details:**
 - Not related to any target related issues.

**Comment by stamparm** [comment]
you are redirecting/pipe-ing the output to something else (most probably file or smth), while something interrupts it (e.g. Ctrl-C or similar). anyhow, with the latest revision it should behave "better"
