### ISSUE TITLE
未处理的异常 (#73976483)

### ISSUE THREAD

**Issue by sqlmapreporter** [sqlmapproject/sqlmap#5304]
```
正在运行的版本: 9.9.9#stable
Python版本: 3.10.2
操作系统: Windows-10-10.0.19044-SP0
命令行: sqlmap.py -r ****** --batch --dbs
技巧: ERROR
后端数据库: MySQL (fingerprinted)
```
```
Traceback (most recent call last):
  File "sqlmap.py", line 221, in main
    start()
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 590, in start
    injection = checkSqlInjection(place, parameter, value)
  File "lib/controller/checks.py", line 853, in checkSqlInjection
    checkSuhosinPatch(injection)
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "lib/controller/checks.py", line 987, in checkSuhosinPatch
    if not checkBooleanExpression("%d=%s%d" % (randInt, ' ' * SUHOSIN_MAX_VALUE_LENGTH, randInt)):
  File "lib/request/inject.py", line 561, in checkBooleanExpression
    return getValue(expression, expected=EXPECTED.BOOL, charsetType=CHARSET_TYPE.BINARY, suppressOutput=True, expectingNone=expectingNone)
  File "lib/core/decorators.py", line 96, in _
    result = f(*args, **kwargs)
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "lib/request/inject.py", line 451, in getValue
    value = errorUse(forgeCaseExpression if expected == EXPECTED.BOOL else query, dump)
  File "lib/techniques/error/use.py", line 467, in errorUse
    debugMsg = "在%.2f秒内执行了 %d 次需要%s" % (kb.counters[getTechnique()], 'y' if kb.counters[getTechnique()] == 1 else "ies", duration)
TypeError: %d format: a real number is required, not str
```

**Comment by stamparm** [comment]
so, somebody is making chinese translated `9.9.9#stable` sqlmap, raising unhandled exceptions on their own fault. highly deserved `FUBAR`
