### ISSUE TITLE
Bug with sqlmaps API?

### ISSUE THREAD

**Issue by preposing** [sqlmapproject/sqlmap#5669]
was playing around with the API and while doing a scan on a site I got the error bellow, its very possible my sqlmap is just outdated:

```
Running version: 1.8.3.13#dev
Python version: 3.10.12
Operating system: Linux-6.5.0-26-generic-x86_64-with-glibc2.35
Command line: sqlmap.py --api -c /tmp/sqlmapconfig-xxwbno2q
Technique: BOOLEAN
Back-end DBMS: Oracle (fingerprinted)
Traceback (most recent call last):
  File "lib/controller/action.py", line 107, in action
    conf.dumper.dbs(conf.dbmsHandler.getDbs())
  File "plugins/generic/databases.py", line 204, in getDbs
    raise SqlmapNoneDataException(errMsg)
lib.core.exception.SqlmapNoneDataException: unable to retrieve the database names

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sqlmap.py", line 222, in main
    start()
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 732, in start
    action()
  File "lib/controller/action.py", line 109, in action
    logger.critical(ex)
  File "/usr/lib/python3.10/logging/__init__.py", line 1524, in critical
    self._log(CRITICAL, msg, args, **kwargs)
  File "/usr/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
  File "lib/utils/api.py", line 279, in emit
    conf.databaseCursor.execute("INSERT INTO logs VALUES(NULL, ?, ?, ?, ?)", (conf.taskid, time.strftime("%X"), record.levelname, record.msg % record.args if record.args else record.msg))
  File "lib/utils/api.py", line 110, in execute
    self.cursor.execute(statement, arguments)
sqlite3.InterfaceError: Error binding parameter 3 - probably unsupported type.
```

**Comment by Aridhi-Dhia-eddine** [comment]
can you send the request here?

**Comment by stamparm** [comment]
Unable to reproduce. Nonetheless, made a "patch"
